In [7]:
import matplotlib.pyplot as plt
import seaborn as sns
import os

colors = ['#537872', '#bd8790', '#706488', '#d0cea3', '#d03f17']

# cath 4.2 test set

In [40]:
recovery_data = {
    "BC-Design (Ours)": 88.03,
    "DIPRoT": 50.6,
    "ProteinMPNN": 50.8,
    "GVP": 40.2,
    "StructTrans": 36.4,
    "StructGNN": 35.91,
    "GraphTrans": 35.82,
    "GCA": 37.64,
    "AlphaDesign": 41.31,
    "PiFold": 51.66,
    "GRADE-IF": 52.21,
    "SPDesign": 67.05,
    "SPIN-CGNN": 54.81,
    "LM-Design": 55.65,
    "ESM-IF": 42.39,
    "VFN-IFE": 62.67,
    "ESM-IF1": 55.25,
    "ProRefiner+ESM-IF1": 57.84,
    "Knowledge-Design": 60.77,
    "MMDesign": 54.88
}

perplexity_data = {
    "BC-Design (Ours)": 1.48,
    "DIPRoT": 4.82,
    "ProteinMPNN": 4.61,
    "GVP": 5.29,
    "StructTrans": 6.85,
    "StructGNN": 6.40,
    "GraphTrans": 6.63,
    "GCA": 6.05,
    "AlphaDesign": 6.30,
    "PiFold": 4.55,
    "SurfPro": 3.31,
    "ESM-IF1": 6.44,
    "GRADE-IF": 4.35,
    "SPDesign": 2.43,
    "SPIN-CGNN": 4.05,
    "LM-Design": 4.52,
    "VFN-IFE": 3.36,
    "Knowledge-Design": 3.46,
    "MMDesign": 3.86
}

common_keys = recovery_data.keys() & perplexity_data.keys()

## recovery rate

In [41]:
# BC-Design (Ours): 88.03
# DIPRoT: 50.6
# ProteinMPNN: 50.8 / 45.96 / 49.87 / 45.16
# GVP: 40.2 / 39.47
# StructTrans: 36.4
# StructGNN: 35.91
# GraphTrans: 35.82
# GCA: 37.64
# AlphaDesign: 41.31
# PiFold: 51.66 / 51.51
# GRADE-IF: 52.21
# SPDesign: 67.05
# SPIN-CGNN: 54.81
# LM-Design: 55.65
# ESM-IF: 42.39
# VFN-IF: 54.74
# VFN-IF+: 57.14
# VFN-IFE: 62.67
# ESM-IF1: 55.25
# ProRefiner+ESM-IF1: 57.84
# Knowledge-Design: 60.77
# MMDesign: 54.88
    
# Data for the bar chart
data = {
    "BC-Design (Ours)": 88.03,
    "DIPRoT": 50.6,
    "ProteinMPNN": 50.8,
    "GVP": 40.2,
    "StructTrans": 36.4,
    "StructGNN": 35.91,
    "GraphTrans": 35.82,
    "GCA": 37.64,
    "AlphaDesign": 41.31,
    "PiFold": 51.66,
    "GRADE-IF": 52.21,
    "SPDesign": 67.05,
    "SPIN-CGNN": 54.81,
    "LM-Design": 55.65,
    "ESM-IF": 42.39,
    "VFN-IFE": 62.67,
    "ESM-IF1": 55.25,
    "ProRefiner+ESM-IF1": 57.84,
    "Knowledge-Design": 60.77,
    "MMDesign": 54.88
}

data = {key: data[key] for key in common_keys}

# Sort the data by values
sorted_data = dict(sorted(data.items(), key=lambda item: item[1], reverse=True))

bar_width = 0.9  # Adjust the bar width as needed
num_bars = len(sorted_data)

# Set the figure width proportional to the number of bars and bar width
fig_width = num_bars * bar_width * 0.6  # Adjust the multiplier (e.g., 2) for spacing between bars

fig = plt.figure(figsize=(fig_width, 8))  # Adjust height as needed

# Setting the figure size
# fig = plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data),
                 width = bar_width)

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Recovery")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

/tmp/ipykernel_536699/3407219283.py:65: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data),

## perplexity

In [42]:
# BC-Design (Ours): 1.4822756730657707
# DIPRoT: 4.82
# ProteinMPNN: 4.74 / 4.61 / 5.25
# GVP: 5.29 / 5.36
# StructTrans: 6.85
# StructGNN: 6.40
# GraphTrans: 6.63
# GCA: 6.05
# AlphaDesign: 6.30
# PiFold: 4.55
# SurfPro: 3.31
# ESM-IF1: 6.44
# GRADE-IF: 4.35
# SPDesign: 2.43
# SPIN-CGNN: 4.05
# LM-Design: 4.52
# VFN-IF: 4.17
# VFN-IF+: 3.66
# VFN-IFE: 3.36
# Knowledge-Design: 3.46
# MMDesign: 3.86
# New data for the bar chart
data_2 = {
    "BC-Design (Ours)": 1.48,
    "DIPRoT": 4.82,
    "ProteinMPNN": 4.61,
    "GVP": 5.29,
    "StructTrans": 6.85,
    "StructGNN": 6.40,
    "GraphTrans": 6.63,
    "GCA": 6.05,
    "AlphaDesign": 6.30,
    "PiFold": 4.55,
    "SurfPro": 3.31,
    "ESM-IF1": 6.44,
    "GRADE-IF": 4.35,
    "SPDesign": 2.43,
    "SPIN-CGNN": 4.05,
    "LM-Design": 4.52,
    "VFN-IFE": 3.36,
    "Knowledge-Design": 3.46,
    "MMDesign": 3.86
}

data_2 = {key: data_2[key] for key in common_keys}

# Sort the data by values
sorted_data_2 = dict(sorted(data_2.items(), key=lambda item: item[1], reverse=False))

bar_width = 0.9  # Adjust the bar width as needed
num_bars = len(sorted_data_2)

# Set the figure width proportional to the number of bars and bar width
fig_width = num_bars * bar_width * 0.6  # Adjust the multiplier (e.g., 2) for spacing between bars

fig = plt.figure(figsize=(fig_width, 8))  # Adjust height as needed

# Setting the figure size
# fig = plt.figure(figsize=(12, 8))

# Create the barplot using the second color in the list
ax = sns.barplot(x=list(sorted_data_2.keys()), y=list(sorted_data_2.values()), palette=[colors[1]] * len(sorted_data_2))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Perplexity")
# plt.title("Comparison of Model Error Rates")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'perplexity.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

/tmp/ipykernel_536699/3512433204.py:62: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  ax = sns.barplot(x=list(sorted_data_2.keys()), y=list(sorted_data_2.values()), palette=[colors[1]] * len(sorted_data_2))

## recovery rate - perplexity

In [10]:
import matplotlib.pyplot as plt
import seaborn as sns
from adjustText import adjust_text

recovery_data = {
    "BC-Design (Ours)": 88.03,
    "DIPRoT": 50.6,
    "ProteinMPNN": 50.8,
    "GVP": 40.2,
    # "StructTrans": 36.4,
    "StructGNN": 35.91,
    "GraphTrans": 35.82,
    "GCA": 37.64,
    "AlphaDesign": 41.31,
    "PiFold": 51.66,
    "GRADE-IF": 52.21,
    "SPDesign": 67.05,
    "SPIN-CGNN": 54.81,
    "LM-Design": 55.65,
    "ESM-IF": 42.39,
    "VFN-IFE": 62.67,
    "ESM-IF1": 55.25,
    "ProRefiner+ESM-IF1": 57.84,
    "Knowledge-Design": 60.77,
    "MMDesign": 54.88
}

perplexity_data = {
    "BC-Design (Ours)": 1.48,
    "DIPRoT": 4.82,
    "ProteinMPNN": 4.61,
    "GVP": 5.29,
    # "StructTrans": 6.85,
    "StructGNN": 6.40,
    "GraphTrans": 6.63,
    "GCA": 6.05,
    "AlphaDesign": 6.30,
    "PiFold": 4.55,
    "SurfPro": 3.31,
    "ESM-IF1": 6.44,
    "GRADE-IF": 4.35,
    "SPDesign": 2.43,
    "SPIN-CGNN": 4.05,
    "LM-Design": 4.52,
    "VFN-IFE": 3.36,
    "Knowledge-Design": 3.46,
    "MMDesign": 3.86
}

common_keys = recovery_data.keys() & perplexity_data.keys()

# Prepare the data for the scatter plot
x_values = [recovery_data[key] for key in common_keys]  # Perplexity (data_2)
y_values = [perplexity_data[key] for key in common_keys]    # Recovery (data)

# Set figure size
fig = plt.figure(figsize=(10, 6))

# Set a custom marker style for the point "BC-Design (Ours)"
markers = ['*' if key == 'BC-Design (Ours)' else 'o' for key in common_keys]

# Create scatter plot with custom markers
for i, key in enumerate(common_keys):
    sns.scatterplot(x=[x_values[i]], y=[y_values[i]], color=colors[1], 
                    marker=markers[i], s=500 if key == 'BC-Design (Ours)' else 100,
                    zorder=2)  # Increased star size to 300

# Add dotted lines for each point connecting only to the bottom (x-axis) and left (y-axis)
for i in range(len(x_values)):
    plt.axvline(x=x_values[i], ymin=0, ymax=(y_values[i]-plt.ylim()[0]) / (plt.ylim()[1]-plt.ylim()[0]), 
                color='gray', linestyle='--', linewidth=0.8, zorder=1)  # Vertical line to bottom
    plt.axhline(y=y_values[i], xmin=0, xmax=(x_values[i]-plt.xlim()[0]) / (plt.xlim()[1]-plt.xlim()[0]), 
                color='gray', linestyle='--', linewidth=0.8, zorder=1)  # Horizontal line to left

# Create label texts for adjustment
texts = [plt.text(x_values[i], y_values[i], key, fontsize=9) for i, key in enumerate(common_keys)]

# Adjust the text positions to avoid overlap
adjust_text(texts, arrowprops=dict(arrowstyle='-', color='gray'))

# Set axis labels
plt.xlabel('Sequence Recovery (%)')
plt.ylabel('Perplexity')

# Display the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_perplexity.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

## nssr

In [77]:
# BC-Design (Ours): 93.23769807815552
# GVP: 60.81
# ProteinMPNN: 60.56
# ProteinMPNN-C: 63.79
# ESM-IF1: 71.56
# ProRefiner+ESM-IF1: 74.11

# New data for the bar chart
data_3 = {
    "BC-Design (Ours)": 93.24,
    "GVP": 60.81,
    "ProteinMPNN": 60.56,
    "ProteinMPNN-C": 63.79,
    "ESM-IF1": 71.56,
    "ProRefiner+ESM-IF1": 74.11
}

# Sort the data by values
sorted_data_3 = dict(sorted(data_3.items(), key=lambda item: item[1], reverse=True))

bar_width = 0.9  # Adjust the bar width as needed
num_bars = len(sorted_data_3)

# Set the figure width proportional to the number of bars and bar width
fig_width = num_bars * bar_width * 0.6  # Adjust the multiplier (e.g., 2) for spacing between bars

fig = plt.figure(figsize=(fig_width, 6))  # Adjust height as needed
# Setting the figure size
# plt.figure(figsize=(10, 6))

# Create the barplot using the second color in the list (vivid orange)
ax = sns.barplot(x=list(sorted_data_3.keys()), y=list(sorted_data_3.values()), palette=[colors[2]] * len(sorted_data_3))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("nssr (%)")
# plt.title("Comparison of Model Accuracy")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

/tmp/ipykernel_536699/4110254848.py:32: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  ax = sns.barplot(x=list(sorted_data_3.keys()), y=list(sorted_data_3.values()), palette=[colors[2]] * len(sorted_data_3))

## TM-score

In [ ]:
# cath 4.2 82
# BC-Design (Ours): 0.7609036564826965
# StructTrans: 0.72
# GVP: 0.73
# ProteinMPNN: 0.80
# PiFold: 0.71
# ByProt: 0.73
# AF-Design: 0.53
# ESM-Design: 0.38

# New data for the bar chart
data_4 = {
    "BC-Design (Ours)": 0.76,
    "StructTrans": 0.72,
    "GVP": 0.73,
    "ProteinMPNN": 0.80,
    "PiFold": 0.71,
    "ByProt": 0.73,
    "AF-Design": 0.53,
    "ESM-Design": 0.38
}

# Sort the data by values
sorted_data_4 = dict(sorted(data_4.items(), key=lambda item: item[1], reverse=True))

# Setting the figure size
plt.figure(figsize=(10, 6))

# Create the barplot using the third color in the list (forest green)
ax = sns.barplot(x=list(sorted_data_4.keys()), y=list(sorted_data_4.values()), palette=[colors[3]] * len(sorted_data_4))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("scTM")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42_82'
file_name = 'sctm.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [46]:
# cath 4.2
# BC-Design (Ours): 0.83
# LM-DESIGN (w/ ProtMPNN encoder): 0.88
# DPLM (w/ ProtMPNN encoder): 0.88

## pLDDT

In [ ]:
# cath 4.2 82
# BC-Design (Ours): 74.92213845252991
# StructTrans: 68.85
# GVP: 69.67
# ProteinMPNN: 76.53
# PiFold: 67.55
# ByProt: 72.12
# AF-Design: 61.37
# ESM-Design: 59.65

# New data for the bar chart
data_5 = {
    "BC-Design (Ours)": 74.92,
    "StructTrans": 68.85,
    "GVP": 69.67,
    "ProteinMPNN": 76.53,
    "PiFold": 67.55,
    "ByProt": 72.12,
    "AF-Design": 61.37,
    "ESM-Design": 59.65
}

# Sort the data by values
sorted_data_5 = dict(sorted(data_5.items(), key=lambda item: item[1], reverse=True))

# Setting the figure size
plt.figure(figsize=(10, 6))

# Create the barplot using the fourth color in the list (Crimson Red)
ax = sns.barplot(x=list(sorted_data_5.keys()), y=list(sorted_data_5.values()), palette=[colors[4]] * len(sorted_data_5))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("pLDDT")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42_82'
file_name = 'plddt.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [48]:
# cath 4.2
# BC-Design (Ours): 81.87
# LM-DESIGN (w/ ProtMPNN encoder): 77.07
# DPLM (w/ ProtMPNN encoder): 77.12

## TM-score - pLDDT

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
from adjustText import adjust_text

tm_data = {
    "BC-Design (Ours)": 0.76,
    "GraphTrans": 0.72,
    "GVP": 0.73,
    "ProteinMPNN": 0.80,
    "PiFold": 0.71,
    "ByProt": 0.73,
    "AF-Design": 0.53,
    "ESM-Design": 0.38
}

plddt_data = {
    "BC-Design (Ours)": 74.92,
    "GraphTrans": 68.85,
    "GVP": 69.67,
    "ProteinMPNN": 76.53,
    "PiFold": 67.55,
    "ByProt": 72.12,
    "AF-Design": 61.37,
    "ESM-Design": 59.65
}

common_keys = tm_data.keys() & plddt_data.keys()

# Prepare the data for the scatter plot
x_values = [tm_data[key] for key in common_keys]  # Perplexity (data_2)
y_values = [plddt_data[key] for key in common_keys]    # Recovery (data)

# Set figure size
fig = plt.figure(figsize=(10, 6))

# Set a custom marker style for the point "BC-Design (Ours)"
markers = ['*' if key == 'BC-Design (Ours)' else 'o' for key in common_keys]

# Create scatter plot with custom markers
for i, key in enumerate(common_keys):
    sns.scatterplot(x=[x_values[i]], y=[y_values[i]], color=colors[0], 
                    marker=markers[i], s=500 if key == 'BC-Design (Ours)' else 100,
                    zorder=2)  # Increased star size to 300

# Add dotted lines for each point connecting only to the bottom (x-axis) and left (y-axis)
for i in range(len(x_values)):
    plt.axvline(x=x_values[i], ymin=0, ymax=(y_values[i]-plt.ylim()[0]) / (plt.ylim()[1]-plt.ylim()[0]), 
                color='gray', linestyle='--', linewidth=0.8, zorder=1)  # Vertical line to bottom
    plt.axhline(y=y_values[i], xmin=0, xmax=(x_values[i]-plt.xlim()[0]) / (plt.xlim()[1]-plt.xlim()[0]), 
                color='gray', linestyle='--', linewidth=0.8, zorder=1)  # Horizontal line to left

# Create label texts for adjustment
texts = [plt.text(x_values[i], y_values[i], key, fontsize=9) for i, key in enumerate(common_keys)]

# Adjust the text positions to avoid overlap
adjust_text(texts, arrowprops=dict(arrowstyle='-', color='gray'))

# Set axis labels
plt.xlabel('Ref-TM')
plt.ylabel('pLDDT')

# Display the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'sctm_plddt.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

# other datasets

## recovery rate

In [ ]:
# Data for the bar chart
data = {
    'CATH 4.2': 88.03,
    'TS50': 93.75864863395691, 
    'TS500': 92.82088875770569,
    'AFDB2000': 75.22448301315308,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Dataset")
plt.ylabel("Recovery")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'recovery.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## perplexity

In [ ]:
# Data for the bar chart
data = {
    'CATH 4.2': 1.48,
    'TS50': 1.1313572824192326, 
    'TS500': 1.2257954277513008,
    'AFDB2000': 5.763193618789838,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Dataset")
plt.ylabel("Perplexity")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'perplexity.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## nssr

In [ ]:
# Data for the bar chart
data = {
    'CATH 4.2': 93.24,
    'TS50': 97.6751983165741, 
    'TS500': 96.66403532028198,
    'AFDB2000': 81.33416771888733,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Dataset")
plt.ylabel("nssr")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'nssr.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## TM-score

In [ ]:
# Data for the bar chart
data = {
    'CATH 4.2': 0.8340755701065063,
    'TS50': 0.8652240037918091, 
    'TS500': 0.867365300655365,
    'AFDB2000': 0.7265705466270447,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Dataset")
plt.ylabel("Ref-TM")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'sctm.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## pLDDT

In [ ]:
# Data for the bar chart
data = {
    'CATH 4.2': 77.76593565940857,
    'TS50': 79.11271452903748, 
    'TS500': 79.90161776542664,
    'AFDB2000': 69.02440786361694,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Dataset")
plt.ylabel("pLDDT")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'plddt.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## all metrics

In [55]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Apply Seaborn style
# sns.set(style="whitegrid")

# Data for 4 datasets and 5 metrics (with Sequence Recovery and Perplexity swapped)
metrics = ['Perplexity', 'Sequence Recovery (%)', 'nssr (%)', 'Ref-TM', 'pLDDT']
values = np.array([
    [1.48, 88.03, 93.24, 0.834, 77.77],   # CATH 4.2 values (Perplexity first, Sequence Recovery second)
    [1.13, 93.76, 97.68, 0.865, 79.11],   # TS50 values (Perplexity first, Sequence Recovery second)
    [1.23, 92.82, 96.66, 0.867, 79.90],   # TS500 values (Perplexity first, Sequence Recovery second)
    [5.76, 75.22, 81.33, 0.727, 69.02]    # AFDB2000 values (Perplexity first, Sequence Recovery second)
])

# Actual ranges of each metric (also adjusted for the swap)
metric_ranges = [
    (0, 6),    # Perplexity
    (0, 100),  # Sequence Recovery (%)
    (0, 100),  # nssr (%)
    (0, 1),    # Ref-TM
    (0, 100)   # pLDDT
]

# Number of variables we're plotting (same as the number of metrics)
num_vars = len(metrics)

# Rescale the values for each metric to a 0-1 range
scaled_values = []
for i in range(len(values)):
    scaled_values.append([
        (values[i][j] - metric_ranges[j][0]) / (metric_ranges[j][1] - metric_ranges[j][0]) 
        for j in range(num_vars)
    ])
scaled_values = np.array(scaled_values)

# Repeat the first value to close the radar chart
scaled_values = np.concatenate([scaled_values, scaled_values[:, [0]]], axis=1)
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

# Start plotting
fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))

# Plot each dataset
colors = sns.color_palette("Set2", len(values))
labels = ['CATH 4.2', 'TS50', 'TS500', 'AFDB2000']
for i in range(len(scaled_values)):
    ax.fill(angles, scaled_values[i], color=colors[i], alpha=0.25, linewidth=2, label=labels[i])
    ax.plot(angles, scaled_values[i], color=colors[i], linewidth=2)

# Add labels for each metric
ax.set_yticklabels([])  # Hide radial grid labels
ax.set_xticks(angles[:-1])
# ax.set_xticklabels(metrics, fontsize=12)
# Remove default x-axis labels
ax.set_xticklabels([])

# Manually place each label at the corresponding angle
for i, metric in enumerate(metrics):
    angle = angles[i]
    angle_degrees = np.degrees(angle)

    if metric == 'Perplexity':
        ax.text(angle, 1.1, metric, size=12)
    elif metric == 'Sequence Recovery (%)':
        ax.text(angle, 1.1, metric, size=12)
    elif metric == 'Ref-TM':
        ax.text(angle, 1.3, metric, size=12)
    elif metric == 'nssr (%)':
        ax.text(angle, 1.3, metric, size=12)
    elif metric == 'pLDDT':
        ax.text(angle, 1.13, metric, size=12)

# Manually set the radial ticks for each metric's axis beside the axis lines
for i, (min_val, max_val) in enumerate(metric_ranges):
    angle = angles[i]  # The angle for the current metric axis
    
    # # Place max value label inside the plot beside the axis (slightly inward)
    # ax.text(angle, 1, f'{max_val}', size=10, color='black')
    metric = metrics[i]
    if metric == 'Perplexity':
        ax.text(angle, 1.02, f'{max_val}', size=10, color='black')
    elif metric == 'Sequence Recovery (%)':
        ax.text(angle, 1.02, f'{max_val}', size=10, color='black')
    elif metric == 'Ref-TM':
        ax.text(angle, 1.07, f'{max_val}', size=10, color='black')
    elif metric == 'nssr (%)':
        ax.text(angle, 1.1, f'{max_val}', size=10, color='black')
    elif metric == 'pLDDT':
        ax.text(angle, 1.06, f'{max_val}', size=10, color='black')

# Place min value label closer to the center beside the axis
ax.text(angle, 0.0, f'0', size=10, color='black')

# Add a legend
plt.legend(loc='upper right', bbox_to_anchor=(0.1, 0.1))

# plt.show()
# Path to save the figure
save_path = './figures/other_datasets'
file_name = 'all_metrics.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

## protein size distribution comparison between 4 test datasets

In [72]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# File paths
files = [
    './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/test_results.csv',
    './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/TS50/test_results.csv',
    './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/TS500/test_results.csv',
    './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'
]

# Reading the CSV files into dataframes
dfs = [pd.read_csv(file) for file in files]

# Adding a column to indicate which dataset the data comes from
labels = ['CATH 4.2', 'TS50', 'TS500', 'AFDB2000']
# Plot each distribution independently
fig = plt.figure(figsize=(6, 6))

colors = sns.color_palette("Set2", len(values))

for i, (df, label) in enumerate(zip(dfs, labels)):
    sns.kdeplot(df['Sequence_Length'], label=label, fill=True, color=colors[i])

# Add title and axis labels
# plt.title('Density Plot of Sequence_Length for Different Datasets (Each Distribution Integrated to 1)')
plt.xlabel('Protein Size')
plt.ylabel('Density')

# Show the legend with clear labels
plt.legend(title='Dataset')

# Add grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)  # Custom grid style

# Display the plot
# plt.show()
# Path to save the figure
save_path = './figures'
file_name = 'protein_sizes4datasets.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

## AFDB2000 divided according to sequence length

In [73]:
colors = ['#537872', '#bd8790', '#706488', '#d0cea3', '#d03f17']

### recovery rate

In [ ]:
# import pandas as pd
# # import numpy as np

# # Specify the path to the CSV file
# file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# # Read the CSV file
# data = pd.read_csv(file_path)

# # Determine the maximum value in the Sequence_Length column
# max_length = data['Sequence_Length'].max()

# # Create bin edges from 0 to the maximum sequence length with a step of 100
# bins = [0, 100, 200, 300, 400, 500, max_length]

# # Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
# data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# # Set up the figure
# plt.figure(figsize=(10, 6))

# # Create a boxplot with binned sequence lengths on the x-axis and recovery on the y-axis
# sns.boxplot(data=data, x='Length_Range', y='Recovery', palette='Set2')

# # Set labels and title
# plt.xlabel('Sequence Length Range')
# plt.ylabel('Recovery')

# # Show the plot
# plt.tight_layout()
# # plt.show()
# # # Path to save the figure
# save_path = './figures/afdb2000'
# file_name = 'recovery_size.png'

# # Create the directory if it doesn't exist
# if not os.path.exists(save_path):
#     os.makedirs(save_path)
# plt.savefig(os.path.join(save_path, file_name))

In [90]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

data['Recovery'] = data['Recovery'] * 100

# Determine the maximum value in the Sequence_Length column
max_length = data['Sequence_Length'].max()

# Create bin edges from 0 to the maximum sequence length with a step of 100
bins = [0, 100, 200, 300, 400, 500, max_length]

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='Recovery', color=colors[0], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('Sequence Recovery (%)')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/afdb2000'
file_name = 'recovery_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### nssr

In [89]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

data['NSSR'] = data['NSSR'] * 100

# Determine the maximum value in the Sequence_Length column
max_length = data['Sequence_Length'].max()

# Create bin edges from 0 to the maximum sequence length with a step of 100
bins = [0, 100, 200, 300, 400, 500, max_length]

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='NSSR', color=colors[2], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('nssr (%)')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/afdb2000'
file_name = 'nssr_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### TM-score

In [92]:
import pandas as pd
# import numpy as np

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Determine the maximum value in the Sequence_Length column
max_length = data['Sequence_Length'].max()

# Create bin edges from 0 to the maximum sequence length with a step of 100
bins = [0, 100, 200, 300, 400, 500, max_length]

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 1)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='TMScore', color=colors[3], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('Ref-TM')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/afdb2000'
file_name = 'sctm_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### pLDDT

In [94]:
import pandas as pd
# import numpy as np

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

data['pLDDT_CA'] = data['pLDDT_CA'] * 100

# Determine the maximum value in the Sequence_Length column
max_length = data['Sequence_Length'].max()

# Create bin edges from 0 to the maximum sequence length with a step of 100
bins = [0, 100, 200, 300, 400, 500, max_length]

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='pLDDT_CA', color=colors[4], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('pLDDT')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/afdb2000'
file_name = 'plddt_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### good large protein case selection
AF-A0A161CEV4-F1-model_v4

In [28]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

In [29]:
data.head()

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,Sequence_Length,Contact_Order,Title
0,0.945255,0.970803,0.889416,0.850692,4.758039,0.9266,0.940171,0.975000,274,0.050898,AF-A1JP86-F1-model_v4
1,0.313653,0.422509,0.276882,0.243231,26.382785,0.2069,0.303609,0.380282,542,0.058794,AF-A1D2R3-F1-model_v4
2,0.956835,0.992806,0.978633,0.963395,3.304645,0.8787,0.952000,1.000000,278,0.072914,AF-A0JUP2-F1-model_v4
3,0.932039,0.966019,0.957621,0.930317,1.569294,0.9641,0.926966,0.964286,206,0.109099,AF-A2CCI1-F1-model_v4
4,0.096317,0.218697,0.191190,0.174906,59.428159,0.1327,0.095601,0.116667,1765,0.011913,AF-A0A0G2K2P5-F1-model_v4

In [33]:
data[(data['Sequence_Length'] > 500) & (data['TMScore'] > 0.8)].sort_values('TMScore', ascending=False)

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,Sequence_Length,Contact_Order,Title
161,0.389864,0.532164,0.689844,0.655048,2.181332,0.9368,0.365909,0.534247,513,0.067949,AF-A2RGS5-F1-model_v4
459,0.425494,0.543986,0.687971,0.660571,3.242437,0.9119,0.403766,0.556962,557,0.061038,AF-A2BQQ9-F1-model_v4
785,0.393891,0.498392,0.662814,0.627821,4.403604,0.9067,0.379439,0.482759,622,0.099485,AF-A0A161CEV4-F1-model_v4
1888,0.396450,0.491124,0.725937,0.686018,3.397391,0.8910,0.382353,0.492308,507,0.063554,AF-A1SZE1-F1-model_v4
1401,0.422311,0.539841,0.617530,0.578860,4.676243,0.8638,0.407895,0.565217,502,0.055056,AF-A1CLZ5-F1-model_v4
578,0.385185,0.500000,0.681037,0.643398,7.600433,0.8595,0.383117,0.397436,540,0.108438,AF-A0QSS4-F1-model_v4
449,0.328302,0.479245,0.662283,0.622910,3.958795,0.8574,0.322314,0.391304,530,0.052571,AF-A1W0F9-F1-model_v4
1077,0.389147,0.486822,0.568930,0.525176,7.187989,0.8528,0.381533,0.450704,645,0.056398,AF-A1WY97-F1-model_v4
506,0.334601,0.431559,0.625818,0.587595,4.953638,0.8504,0.324268,0.437500,526,0.071093,AF-A0A411KUQ5-F1-model_v4
1861,0.379242,0.467066,0.600499,0.567561,5.143813,0.8429,0.375566,0.406780,501,0.053020,AF-A0QT53-F1-model_v4
1380,0.418212,0.514334,0.633305,0.592665,6.942797,0.8355,0.402597,0.574074,593,0.067493,AF-A0A1L9WQQ1-F1-model_v4
1241,0.386588,0.499014,0.658836,0.621837,5.053717,0.8128,0.376106,0.472727,507,0.046728,AF-A1KN60-F1-model_v4
503,0.393443,0.524590,0.586102,0.555339,5.184612,0.8078,0.398773,0.350000,549,0.065717,AF-A0Q355-F1-model_v4

# Validation on partitioned datasets

## cath 4.2

In [4]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Merge the "FewSecondaryStructures" and "Other" classes into "Other"
data['CATH_Class'] = data['CATH_Class'].replace(['FewSecondaryStructures', 'Other'], 'Other')

# Map "AlphaBeta" to "Alpha Beta" for display purposes
data['CATH_Class'] = data['CATH_Class'].replace({'AlphaBeta': 'Alpha Beta'})

data['Recovery'] = data['Recovery'] * 100
data['NSSR'] = data['NSSR'] * 100
data['pLDDT_CA'] = data['pLDDT_CA'] * 100

# Display the DataFrame
data.head()

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,CATH_Class,Sequence_Length,Contact_Order,Core_size,Surface_size,Title
0,90.566040,97.169810,58.547170,0.552976,8.649414,0.4158,0.906250,0.900000,Beta,106,0.119196,10,96,1a1x.A
1,95.370370,99.074070,91.675925,0.881933,0.632792,0.9761,0.951456,1.000000,Alpha Beta,108,0.098140,5,103,1a2p.A
2,91.764706,95.294120,86.235297,0.795423,9.506954,0.7529,0.916667,1.000000,Alpha,85,0.051391,1,84,1a32.A
3,90.123457,93.827160,64.962965,0.628910,14.088815,0.7428,0.901961,0.888889,Alpha Beta,162,0.077646,9,153,1a73.A
4,89.823010,96.460176,95.960176,0.931398,0.779426,0.9824,0.899521,0.882353,Alpha Beta,226,0.073658,17,209,1a8l.A

In [42]:
data[data['Title'] == '2w8x.B']

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,CATH_Class,Sequence_Length,Contact_Order,Core_size,Surface_size,Title
633,96.9697,96.9697,92.09091,0.863781,0.547777,0.9694,0.961538,1.0,Other,66,0.164778,14,52,2w8x.B

### core/surface

#### recovery

In [ ]:
# Specify the file paths
surface_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/surface_recoveries.csv'
core_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/core_recoveries.csv'

# Read the CSV files without headers
surface_data = pd.read_csv(surface_file, header=None, names=['Recovery'])
core_data = pd.read_csv(core_file, header=None, names=['Recovery'])

# Add a new column to differentiate the groups (Surface and Core)
surface_data['Group'] = 'Surface'
core_data['Group'] = 'Core'

# Concatenate the two DataFrames
combined_data = pd.concat([surface_data, core_data])

# Set up the figure
plt.figure(figsize=(8, 6))

# Create the boxplot
sns.boxplot(data=combined_data, x='Group', y='Recovery', palette='Set2')

# Set labels
plt.xlabel('Region')
plt.ylabel('Recovery')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_core_surface.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

#### nssr

In [ ]:
# Specify the file paths
surface_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/surface_nssrs.csv'
core_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/core_nssrs.csv'

# Read the CSV files without headers
surface_data = pd.read_csv(surface_file, header=None, names=['nssr'])
core_data = pd.read_csv(core_file, header=None, names=['nssr'])

# Add a new column to differentiate the groups (Surface and Core)
surface_data['Group'] = 'Surface'
core_data['Group'] = 'Core'

# Concatenate the two DataFrames
combined_data = pd.concat([surface_data, core_data])

# Set up the figure
plt.figure(figsize=(8, 6))

# Create the boxplot
sns.boxplot(data=combined_data, x='Group', y='nssr', palette='Set2')

# Set labels
plt.xlabel('Region')
plt.ylabel('nssr')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr_core_surface.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

#### both

In [198]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Specify the file paths for Recovery and NSSR
surface_recovery_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/surface_recoveries.csv'
core_recovery_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/core_recoveries.csv'
surface_nssr_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/surface_nssrs.csv'
core_nssr_file = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/core_nssrs.csv'

# Read the CSV files for Recovery
surface_recovery_data = pd.read_csv(surface_recovery_file, header=None, names=['Metric'])
core_recovery_data = pd.read_csv(core_recovery_file, header=None, names=['Metric'])

# Read the CSV files for NSSR
surface_nssr_data = pd.read_csv(surface_nssr_file, header=None, names=['Metric'])
core_nssr_data = pd.read_csv(core_nssr_file, header=None, names=['Metric'])

# Add Group and Metric Type columns
surface_recovery_data['Group'] = 'Surface'
core_recovery_data['Group'] = 'Core'
surface_recovery_data['Metric_Type'] = 'Sequence Recovery (%)'
core_recovery_data['Metric_Type'] = 'Sequence Recovery (%)'

surface_nssr_data['Group'] = 'Surface'
core_nssr_data['Group'] = 'Core'
surface_nssr_data['Metric_Type'] = 'nssr (%)'
core_nssr_data['Metric_Type'] = 'nssr (%)'

# Combine the data for both Recovery and NSSR
combined_data = pd.concat([surface_recovery_data, core_recovery_data, surface_nssr_data, core_nssr_data])
combined_data['Metric'] *= 100

# Set up the figure
plt.figure(figsize=(6, 6))

color_map = {'Sequence Recovery (%)': colors[0], 'nssr (%)': colors[2]}

# Create the boxplot
sns.boxplot(data=combined_data, x='Group', y='Metric', hue='Metric_Type', palette=color_map)

# Set labels and limits
plt.xlabel('Region')
plt.ylabel('Value')
plt.ylim(0, 100)

# Add grid for better readability
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Add legend
plt.legend(loc='lower left')

# Show the plot layout
plt.tight_layout()

# Save the combined plot
save_path = './figures/cath42'
file_name = 'recovery_nssr_core_surface.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close()

### cath class

#### recovery

In [ ]:
# Define the custom order for x-axis sorting
order = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot using seaborn
sns.boxplot(data=data, x='CATH_Class', y='Recovery', order=order, palette='Set2')

# Set labels and title
plt.xlabel('CATH Class')
plt.ylabel('Recovery')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_cath_class.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

#### nssr

In [ ]:
# Define the custom order for x-axis sorting
order = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot using seaborn
sns.boxplot(data=data, x='CATH_Class', y='NSSR', order=order, palette='Set2')

# Set labels and title
plt.xlabel('CATH Class')
plt.ylabel('nssr')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr_cath_class.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

#### plddt

##### visualization

In [ ]:
# Define the custom order for x-axis sorting
order = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot using seaborn
sns.boxplot(data=data, x='CATH_Class', y='pLDDT_CA', order=order, palette='Set2')

# Set labels and title
plt.xlabel('CATH Class')
plt.ylabel('pLDDT')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'plddt_cath_class.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

##### statistical test

In [ ]:
from scipy.stats import kruskal

# Assuming the data is already provided as 'data', with 'CATH_Class' and 'pLDDT_CA' columns

# Extract the data for each group
alpha = data[data['CATH_Class'] == 'Alpha']['pLDDT_CA']
beta = data[data['CATH_Class'] == 'Beta']['pLDDT_CA']
alpha_beta = data[data['CATH_Class'] == 'Alpha Beta']['pLDDT_CA']
other = data[data['CATH_Class'] == 'Other']['pLDDT_CA']

# Perform Kruskal-Wallis test
kruskal_test_result = kruskal(alpha, beta, alpha_beta, other)

kruskal_test_result

In [ ]:
from scikit_posthocs import posthoc_dunn
import numpy as np

# Perform Dunn's test for pairwise comparisons
dunn_test_result = posthoc_dunn([data[data['CATH_Class'] == 'Alpha']['pLDDT_CA'],
                                 data[data['CATH_Class'] == 'Beta']['pLDDT_CA'],
                                 data[data['CATH_Class'] == 'Alpha Beta']['pLDDT_CA'],
                                 data[data['CATH_Class'] == 'Other']['pLDDT_CA']],
                                p_adjust = 'bonferroni')

# Label the columns and rows
dunn_test_result.index = ['Alpha', 'Beta', 'Alpha Beta', 'Other']
dunn_test_result.columns = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

dunn_test_result

#### scTM

##### visualization

In [ ]:
# Define the custom order for x-axis sorting
order = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot using seaborn
sns.boxplot(data=data, x='CATH_Class', y='TMScore', order=order, palette='Set2')

# Set labels and title
plt.xlabel('CATH Class')
plt.ylabel('scTM')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'sctm_cath_class.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

##### statistical test

In [ ]:
from scipy.stats import kruskal

# Assuming the data is already provided as 'data', with 'CATH_Class' and 'pLDDT_CA' columns

# Extract the data for each group
alpha = data[data['CATH_Class'] == 'Alpha']['TMScore']
beta = data[data['CATH_Class'] == 'Beta']['TMScore']
alpha_beta = data[data['CATH_Class'] == 'Alpha Beta']['TMScore']
other = data[data['CATH_Class'] == 'Other']['TMScore']

# Perform Kruskal-Wallis test
kruskal_test_result = kruskal(alpha, beta, alpha_beta, other)

kruskal_test_result

In [ ]:
from scikit_posthocs import posthoc_dunn
import numpy as np

# Perform Dunn's test for pairwise comparisons
dunn_test_result = posthoc_dunn([data[data['CATH_Class'] == 'Alpha']['TMScore'],
                                 data[data['CATH_Class'] == 'Beta']['TMScore'],
                                 data[data['CATH_Class'] == 'Alpha Beta']['TMScore'],
                                 data[data['CATH_Class'] == 'Other']['TMScore']],
                                p_adjust = 'bonferroni')

# Label the columns and rows
dunn_test_result.index = ['Alpha', 'Beta', 'Alpha Beta', 'Other']
dunn_test_result.columns = ['Alpha', 'Beta', 'Alpha Beta', 'Other']

dunn_test_result

#### all metrics

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import parallel_coordinates

# Calculate the median of each metric for each class type
metrics_data = data[['CATH_Class', 'Recovery', 'NSSR', 'TMScore', 'pLDDT_CA']].groupby('CATH_Class').median().reset_index()

# Rename the columns to match the plot labels
metrics_data.rename(columns={'Recovery': 'Sequence Recovery (%)', 'NSSR': 'nssr (%)', 
                             'TMScore': 'Ref-TM', 'pLDDT_CA': 'pLDDT'}, inplace=True)

# Convert Ref-TM to percentage for consistency
metrics_data['Ref-TM'] *= 100

# Create a parallel coordinates plot
fig = plt.figure(figsize=(6, 6))
# Set the color palette explicitly using Seaborn
palette = sns.color_palette("Dark2", len(metrics_data['CATH_Class'].unique()))

parallel_coordinates(metrics_data, class_column='CATH_Class', 
                     cols=['Sequence Recovery (%)', 'nssr (%)', 'Ref-TM', 'pLDDT'],
                     color=palette, zorder=3)

# Set the y-axis limit to 0-100 for consistency
plt.ylim(0, 100)

# Remove the original y-ticks
plt.gca().tick_params(axis='y', which='both', left=False, right=False, labelleft=False)

# Add manual text annotations for each metric and shift them slightly to the right
metrics = ['Sequence Recovery (%)', 'nssr (%)', 'Ref-TM', 'pLDDT']
positions = [0, 1, 2, 3]  # Corresponds to the metric x-axis positions

for pos, metric in zip(positions, metrics):
    if metric == 'Ref-TM':  # Metric that ranges from 0 to 1
        labels = ['0', '0.2', '0.4', '0.6', '0.8', '1']
        values = [0, 20, 40, 60, 80, 100]
    else:  # Metrics that range from 0 to 100
        labels = ['0', '20', '40', '60', '80', '100']
        values = [0, 20, 40, 60, 80, 100]
    
    # Add labels at positions slightly shifted to the right (pos + 0.05)
    for label, value in zip(labels, values):
        plt.text(pos + 0.07, value + 1, label, horizontalalignment='center', verticalalignment='center')

scaled_data = data.copy()
scaled_data['TMScore'] *= 100

# Map class names to colors
class_colors = dict(zip(metrics_data['CATH_Class'].unique(), palette))
# Overlay box plots for each metric
for class_name, color in class_colors.items():
    for i, metric in enumerate(['Recovery', 'NSSR', 'TMScore', 'pLDDT_CA']):
        sns.boxplot(x=[i] * len(scaled_data[scaled_data['CATH_Class'] == class_name]), 
                    y=metric, 
                    data=scaled_data[scaled_data['CATH_Class'] == class_name], 
                    width=0.2, 
                    boxprops=dict(alpha=0.3), 
                    showfliers=False, 
                    whiskerprops={'color': color, 'linewidth': 2}, 
                    capprops={'color': color, 'linewidth': 2}, 
                    palette=[color], zorder=2)

# Add grid for better readability
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Set axis labels
plt.xlabel('Metrics')
plt.ylabel('Values')

# Add the legend and place it at the left-bottom corner
plt.legend(loc='lower left',)

# Show the plot layout
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'all_metrics_cath_class.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### size

In [ ]:
# Determine the maximum value in the Sequence_Length column
max_length = data['Sequence_Length'].max()

# Create bin edges from 0 to the maximum sequence length with a step of 100
bins = np.arange(0, max_length + 100, 100)

# Set up the figure
plt.figure(figsize=(10, 6))

# Create the histogram
sns.histplot(data['Sequence_Length'], bins=bins, kde=False, color='skyblue')

# Set labels and title
plt.xlabel('Sequence Length')
plt.ylabel('Frequency')

# Show the plot
plt.tight_layout()
plt.show()

#### recovery

In [ ]:
import numpy as np

# Define bin edges for sequence lengths (0, 100, 200, ..., max)
bins = np.arange(0, data['Sequence_Length'].max() + 100, 100)

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='Recovery', color=colors[0], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('Sequence Recovery (%)')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### nssr

In [99]:
# Define bin edges for sequence lengths (0, 100, 200, ..., max)
bins = np.arange(0, data['Sequence_Length'].max() + 100, 100)

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='NSSR', color=colors[2], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('nssr (%)')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### plddt

In [ ]:
# Define bin edges for sequence lengths (0, 100, 200, ..., max)
bins = np.arange(0, data['Sequence_Length'].max() + 100, 100)

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 100)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='pLDDT_CA', color=colors[4], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('pLDDT')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/cath42'
file_name = 'plddt_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### scTM

In [102]:
# Define bin edges for sequence lengths (0, 100, 200, ..., max)
bins = np.arange(0, data['Sequence_Length'].max() + 100, 100)

# Bin the Sequence_Length column into categories (0-100, 100-200, etc.)
data['Length_Range'] = pd.cut(data['Sequence_Length'], bins=bins, right=False)

# Set up the figure
fig = plt.figure(figsize=(6, 6))

plt.ylim(0, 1)

# Create a violin plot with binned sequence lengths on the x-axis and recovery on the y-axis
sns.violinplot(data=data, x='Length_Range', y='TMScore', color=colors[3], width=0.99)

# Set labels and title
plt.xlabel('Protein Size')
plt.ylabel('Ref-TM')

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Show the plot layout
plt.tight_layout()

# Path to save the figure
save_path = './figures/cath42'
file_name = 'sctm_size.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### structural complexity (contact order)

#### recovery

In [ ]:
# Define bin edges for Contact_Order (0, 0.1, 0.2, ..., max)
bins = np.arange(0, data['Contact_Order'].max() + 0.05, 0.05)

# Bin the Contact_Order column into categories (0-0.1, 0.1-0.2, etc.)
data['Contact_Order_Range'] = pd.cut(data['Contact_Order'], bins=bins, right=False)

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot with binned contact order on the x-axis and recovery on the y-axis
sns.boxplot(data=data, x='Contact_Order_Range', y='Recovery', palette='Set2')

# Set labels and title
plt.xlabel('Contact Order Range')
plt.ylabel('Recovery')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_contact_order.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [116]:
# scatterplot, deprecated
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import os

# # Load data
# contact_orders = np.load('./test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/contact_orders.npy')
# recoveries = np.load('./test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/recoveries.npy')

# # Create a DataFrame
# data = pd.DataFrame({'Contact Orders': contact_orders, 'Recoveries': recoveries * 100})

# LOESS fit
frac = 0.3
# lowess = sm.nonparametric.lowess(data['Recoveries'], data['Contact Orders'], frac=frac)
lowess = sm.nonparametric.lowess(data['Recovery'], data['Contact_Order'], frac=frac)
x_fit = lowess[:, 0]
y_fit = lowess[:, 1]

# Bootstrapping to calculate confidence intervals
n_bootstraps = 1000
predictions = np.zeros((n_bootstraps, len(x_fit)))

for i in range(n_bootstraps):
    # Resample data with replacement
    bootstrap_sample = data.sample(frac=1, replace=True)
    lowess_bs = sm.nonparametric.lowess(bootstrap_sample['Recovery'], bootstrap_sample['Contact_Order'], frac=frac)
    predictions[i, :] = lowess_bs[:, 1]

# Calculate confidence intervals
ci_lower = np.percentile(predictions, 2.5, axis=0)
ci_upper = np.percentile(predictions, 97.5, axis=0)

In [119]:
# Scatter plot
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(x='Contact_Order', y='Recovery', data=data, alpha=0.5, color=colors[0])

# Plot LOESS curve
plt.plot(x_fit, y_fit, color='red', label='LOWESS Fit')

# Plot confidence intervals
plt.fill_between(x_fit, ci_lower, ci_upper, color='red', alpha=0.2, label='95% CI')

# Labels and title
plt.xlabel('Contact Order')
plt.ylabel('Sequence Recovery (%)')

plt.ylim(0, 100)

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)
# plt.title('LOESS Fit with Varying Confidence Intervals')
plt.legend()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'recovery_contact_order_scatter.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### nssr

In [ ]:
# Define bin edges for Contact_Order (0, 0.1, 0.2, ..., max)
bins = np.arange(0, data['Contact_Order'].max() + 0.05, 0.05)

# Bin the Contact_Order column into categories (0-0.1, 0.1-0.2, etc.)
data['Contact_Order_Range'] = pd.cut(data['Contact_Order'], bins=bins, right=False)

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot with binned contact order on the x-axis and recovery on the y-axis
sns.boxplot(data=data, x='Contact_Order_Range', y='NSSR', palette='Set2')

# Set labels and title
plt.xlabel('Contact Order Range')
plt.ylabel('nssr')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr_contact_order.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [120]:
# scatterplot, deprecated
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import os

# LOESS fit
frac = 0.3
# lowess = sm.nonparametric.lowess(data['Recoveries'], data['Contact Orders'], frac=frac)
lowess = sm.nonparametric.lowess(data['NSSR'], data['Contact_Order'], frac=frac)
x_fit = lowess[:, 0]
y_fit = lowess[:, 1]

# Bootstrapping to calculate confidence intervals
n_bootstraps = 1000
predictions = np.zeros((n_bootstraps, len(x_fit)))

for i in range(n_bootstraps):
    # Resample data with replacement
    bootstrap_sample = data.sample(frac=1, replace=True)
    lowess_bs = sm.nonparametric.lowess(bootstrap_sample['NSSR'], bootstrap_sample['Contact_Order'], frac=frac)
    predictions[i, :] = lowess_bs[:, 1]

# Calculate confidence intervals
ci_lower = np.percentile(predictions, 2.5, axis=0)
ci_upper = np.percentile(predictions, 97.5, axis=0)

In [123]:
# Scatter plot
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(x='Contact_Order', y='NSSR', data=data, alpha=0.5, color=colors[2])

# Plot LOESS curve
plt.plot(x_fit, y_fit, color='red', label='LOWESS Fit')

# Plot confidence intervals
plt.fill_between(x_fit, ci_lower, ci_upper, color='red', alpha=0.2, label='95% CI')

# Labels and title
plt.xlabel('Contact Order')
plt.ylabel('nssr (%)')

plt.ylim(0, 100)

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)
# plt.title('LOESS Fit with Varying Confidence Intervals')
plt.legend()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'nssr_contact_order_scatter.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### plddt

In [ ]:
# Define bin edges for Contact_Order (0, 0.1, 0.2, ..., max)
bins = np.arange(0, data['Contact_Order'].max() + 0.05, 0.05)

# Bin the Contact_Order column into categories (0-0.1, 0.1-0.2, etc.)
data['Contact_Order_Range'] = pd.cut(data['Contact_Order'], bins=bins, right=False)

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot with binned contact order on the x-axis and recovery on the y-axis
sns.boxplot(data=data, x='Contact_Order_Range', y='pLDDT_CA', palette='Set2')

# Set labels and title
plt.xlabel('Contact Order Range')
plt.ylabel('pLDDT')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'plddt_contact_order.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [124]:
# scatterplot, deprecated
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import os

# LOESS fit
frac = 0.3
# lowess = sm.nonparametric.lowess(data['Recoveries'], data['Contact Orders'], frac=frac)
lowess = sm.nonparametric.lowess(data['pLDDT_CA'], data['Contact_Order'], frac=frac)
x_fit = lowess[:, 0]
y_fit = lowess[:, 1]

# Bootstrapping to calculate confidence intervals
n_bootstraps = 1000
predictions = np.zeros((n_bootstraps, len(x_fit)))

for i in range(n_bootstraps):
    # Resample data with replacement
    bootstrap_sample = data.sample(frac=1, replace=True)
    lowess_bs = sm.nonparametric.lowess(bootstrap_sample['pLDDT_CA'], bootstrap_sample['Contact_Order'], frac=frac)
    predictions[i, :] = lowess_bs[:, 1]

# Calculate confidence intervals
ci_lower = np.percentile(predictions, 2.5, axis=0)
ci_upper = np.percentile(predictions, 97.5, axis=0)

In [127]:
# Scatter plot
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(x='Contact_Order', y='pLDDT_CA', data=data, alpha=0.5, color=colors[4])

# Plot LOESS curve
plt.plot(x_fit, y_fit, color='red', label='LOWESS Fit')

# Plot confidence intervals
plt.fill_between(x_fit, ci_lower, ci_upper, color='red', alpha=0.2, label='95% CI')

# Labels and title
plt.xlabel('Contact Order')
plt.ylabel('pLDDT')

plt.ylim(0, 100)

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)
# plt.title('LOESS Fit with Varying Confidence Intervals')
plt.legend()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'plddt_contact_order_scatter.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

#### scTM

In [ ]:
# Define bin edges for Contact_Order (0, 0.1, 0.2, ..., max)
bins = np.arange(0, data['Contact_Order'].max() + 0.05, 0.05)

# Bin the Contact_Order column into categories (0-0.1, 0.1-0.2, etc.)
data['Contact_Order_Range'] = pd.cut(data['Contact_Order'], bins=bins, right=False)

# Set up the figure
plt.figure(figsize=(10, 6))

# Create a boxplot with binned contact order on the x-axis and recovery on the y-axis
sns.boxplot(data=data, x='Contact_Order_Range', y='TMScore', palette='Set2')

# Set labels and title
plt.xlabel('Contact Order Range')
plt.ylabel('scTM')

# Show the plot
plt.tight_layout()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'sctm_contact_order.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [128]:
# scatterplot, deprecated
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import os

# LOESS fit
frac = 0.3
# lowess = sm.nonparametric.lowess(data['Recoveries'], data['Contact Orders'], frac=frac)
lowess = sm.nonparametric.lowess(data['TMScore'], data['Contact_Order'], frac=frac)
x_fit = lowess[:, 0]
y_fit = lowess[:, 1]

# Bootstrapping to calculate confidence intervals
n_bootstraps = 1000
predictions = np.zeros((n_bootstraps, len(x_fit)))

for i in range(n_bootstraps):
    # Resample data with replacement
    bootstrap_sample = data.sample(frac=1, replace=True)
    lowess_bs = sm.nonparametric.lowess(bootstrap_sample['TMScore'], bootstrap_sample['Contact_Order'], frac=frac)
    predictions[i, :] = lowess_bs[:, 1]

# Calculate confidence intervals
ci_lower = np.percentile(predictions, 2.5, axis=0)
ci_upper = np.percentile(predictions, 97.5, axis=0)

In [ ]:
# Scatter plot
fig = plt.figure(figsize=(10, 6))
sns.scatterplot(x='Contact_Order', y='TMScore', data=data, alpha=0.5, color=colors[3])

# Plot LOESS curve
plt.plot(x_fit, y_fit, color='red', label='LOWESS Fit')

# Plot confidence intervals
plt.fill_between(x_fit, ci_lower, ci_upper, color='red', alpha=0.2, label='95% CI')

# Labels and title
plt.xlabel('Contact Order')
plt.ylabel('Ref-TM')

plt.ylim(0, 1)

# Add a grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)
# plt.title('LOESS Fit with Varying Confidence Intervals')
plt.legend()
# plt.show()
# Path to save the figure
save_path = './figures/cath42'
file_name = 'sctm_contact_order_scatter.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### residue-level metrics

In [202]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Data provided (formatted into a dictionary for easier conversion to DataFrame)
data = {
    'A': {
        'accuracy': 0.9849, 'f1': 0.9045, 'precision': 0.8867, 'recall': 0.9230
    },
    'C': {
        'accuracy': 0.9978, 'f1': 0.9144, 'precision': 0.9404, 'recall': 0.8898
    },
    'D': {
        'accuracy': 0.9558, 'f1': 0.5899, 'precision': 0.6747, 'recall': 0.5241
    },
    'E': {
        'accuracy': 0.9502, 'f1': 0.6915, 'precision': 0.6284, 'recall': 0.7686
    },
    'F': {
        'accuracy': 0.9925, 'f1': 0.9138, 'precision': 0.9368, 'recall': 0.8920
    },
    'G': {
        'accuracy': 0.9934, 'f1': 0.9507, 'precision': 0.9351, 'recall': 0.9668
    },
    'H': {
        'accuracy': 0.9965, 'f1': 0.9227, 'precision': 0.9495, 'recall': 0.8974
    },
    'I': {
        'accuracy': 0.9898, 'f1': 0.9122, 'precision': 0.9235, 'recall': 0.9012
    },
    'K': {
        'accuracy': 0.9890, 'f1': 0.9109, 'precision': 0.9023, 'recall': 0.9197
    },
    'L': {
        'accuracy': 0.9809, 'f1': 0.8986, 'precision': 0.8722, 'recall': 0.9266
    },
    'M': {
        'accuracy': 0.9932, 'f1': 0.8357, 'precision': 0.8836, 'recall': 0.7927
    },
    'N': {
        'accuracy': 0.9705, 'f1': 0.6425, 'precision': 0.6538, 'recall': 0.6316
    },
    'P': {
        'accuracy': 0.9961, 'f1': 0.9559, 'precision': 0.9297, 'recall': 0.9836
    },
    'Q': {
        'accuracy': 0.9731, 'f1': 0.6419, 'precision': 0.6601, 'recall': 0.6246
    },
    'R': {
        'accuracy': 0.9923, 'f1': 0.9218, 'precision': 0.9446, 'recall': 0.9002
    },
    'S': {
        'accuracy': 0.9901, 'f1': 0.9151, 'precision': 0.9163, 'recall': 0.9139
    },
    'T': {
        'accuracy': 0.9909, 'f1': 0.9156, 'precision': 0.9279, 'recall': 0.9036
    },
    'V': {
        'accuracy': 0.9866, 'f1': 0.9084, 'precision': 0.9045, 'recall': 0.9123
    },
    'W': {
        'accuracy': 0.9981, 'f1': 0.9246, 'precision': 0.9612, 'recall': 0.8906
    },
    'Y': {
        'accuracy': 0.9937, 'f1': 0.9097, 'precision': 0.9341, 'recall': 0.8866
    }
}

# Convert to DataFrame
df = pd.DataFrame(data).T.reset_index()
df.columns = ['Amino Acid', 'Accuracy', 'F1-Score', 'Precision', 'Recall']

# Melt the DataFrame for seaborn
df_melted = df.melt(id_vars='Amino Acid', var_name='Metric', value_name='Value')

# Set up the figure
fig = plt.figure(figsize=(12, 8))

# Create bar plots for each metric using seaborn, with a different color palette
sns.barplot(data=df_melted, x='Amino Acid', y='Value', hue='Metric', palette='coolwarm', zorder=2)

# Set x-tick labels without rotation
plt.xticks(rotation=0)

# Add a grid for better readability
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Set y-axis limits to (0, 1)
plt.ylim(0, 1)

# Move legend to the right
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))  

# Adjust layout to fit well
plt.tight_layout()

# Save the figure
save_path = './figures/cath42'
file_name = 'residue_level.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

# ablation

In [ ]:
# full: 0.8803263306617737
# w.o. correspondence: 0.42445188760757446
# w.o. structure feature: 0.8360046148300171
# w.o. edge feature: 0.8718589544296265
# w.o. node feature: 0.8472650051116943
# w.o. biochem. feature: 0.3220404386520386
# w.o. hydrophobicity: 0.2150287926197052
# w.o. charge: 0.8264081478118896

## recovery rate

In [14]:
# Data for the bar chart
data = {
    "Full": 88.03,
    "w/o BC-Graph": 39.56163823604584,
    "w/o Biochem. Feature": 33.724698424339294,
    "w/o Struc. Feature": 83.79876613616943,
    "w/o Hydrophobicity": 50.85405111312866,
    "w/o Charge": 83.54751467704773,
    "w/o Node Feature": 86.48642301559448,
    "w/o Edge Feature": 87.2209906578064,
}

# Sort the data by values
sorted_data = data

bar_width = 0.9  # Adjust the bar width as needed
num_bars = len(sorted_data)

# Set the figure width proportional to the number of bars and bar width
fig_width = num_bars * bar_width * 0.6  # Adjust the multiplier (e.g., 2) for spacing between bars

fig = plt.figure(figsize=(fig_width, 6))  # Adjust height as needed
# Setting the figure size
# plt.figure(figsize=(10, 6))

# Create the barplot using the second color in the list (vivid orange)
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Sequence Recovery (%)")
# plt.title("Comparison of Model Accuracy")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42/ablation'
file_name = 'recovery.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

/tmp/ipykernel_372503/181902726.py:27: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

## perplexity

In [ ]:
# Data for the bar chart
data = {
    "Full": 1.483301282116166,
    "w/o BC-Graph": 6.5636352266571585,
    "w/o Biochem. Feature": 8.013347405081028,
    "w/o Struc. Feature": 1.6685742108200694,
    "w/o Hydrophobicity": 4.139218637988384,
    "w/o Charge": 1.6593299853875612,
    "w/o Node Feature": 1.552204151608043,
    "w/o Edge Feature": 1.5246874807266404,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Perplexity")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42/ablation'
file_name = 'perplexity.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## nssr

In [ ]:
# Data for the bar chart
data = {
    "Full": 93.23837161064148,
    "w/o BC-Graph": 57.46558308601379,
    "w/o Biochem. Feature": 53.5994291305542,
    "w/o Struc. Feature": 90.44122099876404,
    "w/o Hydrophobicity": 71.78291082382202,
    "w/o Charge": 92.68889427185059,
    "w/o Node Feature": 92.09948182106018,
    "w/o Edge Feature": 92.58340001106262,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("nssr")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42/ablation'
file_name = 'nssr.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## TM-score

In [ ]:
# Data for the bar chart
data = {
    "Full": 0.8340755701065063,
    "w/o BC-Graph": 0.7048928141593933,
    "w/o Biochem. Feature": 0.6870874762535095,
    "w/o Struc. Feature": 0.7961016893386841,
    "w/o Hydrophobicity": 0.7521645426750183,
    "w/o Charge":  0.8302716016769409,
    "w/o Node Feature": 0.8205986022949219,
    "w/o Edge Feature": 0.8171550035476685,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Ref-TM")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.3f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42/ablation'
file_name = 'sctm.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

## pLDDT

In [ ]:
# Data for the bar chart
data = {
    "Full": 77.76593565940857,
    "w/o BC-Graph": 64.37565684318542,
    "w/o Biochem. Feature": 63.7636661529541,
    "w/o Struc. Feature": 76.22922658920288,
    "w/o Hydrophobicity": 68.63343119621277,
    "w/o Charge":  77.34217643737793,
    "w/o Node Feature": 76.56629085540771,
    "w/o Edge Feature": 76.41912698745728,
}

# Sort the data by values
sorted_data = data

# Setting the figure size
plt.figure(figsize=(12, 8))

# Create the barplot
ax = sns.barplot(x=list(sorted_data.keys()), y=list(sorted_data.values()), palette=[colors[0]] * len(sorted_data))

# Set the x-axis labels to rotate by 90 degrees
plt.xticks(rotation=90)

# Add labels and title
plt.xlabel("Model")
plt.ylabel("Ref-TM")
# plt.title("Comparison of Model Performance")

# Add value labels on top of each bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9), textcoords = 'offset points')

# Make the plot layout tighter
plt.tight_layout()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/cath42/ablation'
file_name = 'sctm.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

# analysis

## protein selection

### Good cases for cath4.2 high, median, low CO
### Good cases for 4 cath4.2 classes
low CO (alpha):

1y66.A

1ojh.A

4bw5.C

median CO (alpha beta):

3kp8.A

high CO (beta):

4pif.A

other:

2w8x.B

1bik.A

In [41]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Merge the "FewSecondaryStructures" and "Other" classes into "Other"
data['CATH_Class'] = data['CATH_Class'].replace(['FewSecondaryStructures', 'Other'], 'Other')

# Map "AlphaBeta" to "Alpha Beta" for display purposes
data['CATH_Class'] = data['CATH_Class'].replace({'AlphaBeta': 'Alpha Beta'})

data_sorted = data.sort_values(by='Contact_Order', ascending=True)

In [ ]:
data_sorted[data_sorted['Contact_Order'] < 0.05].sort_values(by=['Recovery', 'TMScore'], ascending=False)

In [ ]:
data_sorted[(data_sorted['Contact_Order'] >= 0.1) & (data_sorted['Contact_Order'] < 0.15) & \
            (data_sorted['Recovery'] > 0.95) & (data_sorted['TMScore'] > 0.95) & (data_sorted['pLDDT_CA'] > 0.95)]\
        .sort_values(by=['Recovery', 'TMScore'], ascending=False)

In [ ]:
data_sorted[(data_sorted['Contact_Order'] >= 0.2) & (data_sorted['Contact_Order'] < 0.25) & \
            (data_sorted['Recovery'] > 0.9) & (data_sorted['TMScore'] > 0.9) & (data_sorted['pLDDT_CA'] > 0.9)]\
        .sort_values(by=['Recovery', 'TMScore'], ascending=False)

In [ ]:
data_sorted[(data_sorted['CATH_Class'] == 'Other') & \
            (data_sorted['Recovery'] > 0.9) & (data_sorted['TMScore'] > 0.9) & (data_sorted['pLDDT_CA'] > 0.9)]\
        .sort_values(by=['Recovery', 'TMScore'], ascending=False)

### (not now) Good cases for large cath4.2 proteins (+ig)
['2h8p.C',
 '1g6u.A',
 '3ous.A',
 '1s5h.C',
 '2ksd.A',
 '1bha.A',
 '1tp6.A',
 '2nn4.A',
 '3h3h.A',
 '1d2d.A']

In [113]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Merge the "FewSecondaryStructures" and "Other" classes into "Other"
data['CATH_Class'] = data['CATH_Class'].replace(['FewSecondaryStructures', 'Other'], 'Other')

# Map "AlphaBeta" to "Alpha Beta" for display purposes
data['CATH_Class'] = data['CATH_Class'].replace({'AlphaBeta': 'Alpha Beta'})

In [116]:
data[data['Recovery'] > 0.95].sort_values(by='Recovery', ascending=False)['Title'][: 10].tolist()

['2h8p.C',
 '1g6u.A',
 '3ous.A',
 '1s5h.C',
 '2ksd.A',
 '1bha.A',
 '1tp6.A',
 '2nn4.A',
 '3h3h.A',
 '1d2d.A']

#### ig

In [11]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

def draw_cath42_ig(title):
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
    surface_coords = data['surface']         # Shape (n, 3)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Extract the coordinates of each point
    x_coords = surface_coords[:, 0]
    y_coords = surface_coords[:, 1]
    z_coords = surface_coords[:, 2]

    # Create a 3D scatter plot
    fig = plt.figure(figsize=(7, 5))
    ax = fig.add_subplot(111, projection='3d')

    # Set the background color to grey
    ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

    # Create a custom normalization centered around zero using TwoSlopeNorm
    # vmin = np.min(first_values)
    # vmax = np.max(first_values)
    vmin = np.percentile(first_values, 1)  # 10th percentile
    vmax = np.percentile(first_values, 99)  # 90th percentile
    abs_max = np.max([np.abs(vmin), np.abs(vmax)])
    norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

    # Scatter plot with colors representing the first values
    sc = ax.scatter(
        x_coords, y_coords, z_coords, 
        c=first_values, 
        cmap='seismic', 
        norm=norm,
        marker='o', 
        s=1
    )

    # Add color bar to indicate value distribution
    cbar = plt.colorbar(sc, ax=ax)
    # cbar.set_label('First Value of grads_A (white represents neutral)')

    # Reduce the size of the color bar
    cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

    # Remove ticks from the plot
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])

    ax.set_axis_off()

    # Set the elevation to 0
    ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

    # Show plot
    # plt.show()
    # Path to save the figure
    save_path = './figures/ig/good_cath42_cases_99percentile'
    file_name = f'{title}.png'

    # Create the directory if it doesn't exist
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    plt.savefig(os.path.join(save_path, file_name))
    plt.close(fig)

In [12]:
titles = ['2h8p.C',
 '1g6u.A',
 '3ous.A',
 '1s5h.C',
 '2ksd.A',
 '1bha.A',
 '1tp6.A',
 '2nn4.A',
 '3h3h.A',
 '1d2d.A']

for title in titles:
    draw_cath42_ig(title)

### Proteins that have good core prediction and bad surface prediction (+ig)
2l2f.A
3mvg.A

In [76]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Merge the "FewSecondaryStructures" and "Other" classes into "Other"
data['CATH_Class'] = data['CATH_Class'].replace(['FewSecondaryStructures', 'Other'], 'Other')

# Map "AlphaBeta" to "Alpha Beta" for display purposes
data['CATH_Class'] = data['CATH_Class'].replace({'AlphaBeta': 'Alpha Beta'})

data_sorted = data.sort_values(by='Contact_Order', ascending=True)

In [ ]:
data_sorted[(data_sorted['Recovery'] - data_sorted['Surface Recovery'] > 0.02)]\
        .sort_values(by='Surface Recovery', ascending=True)

#### ig

In [ ]:
import pickle

# Define the path to the file
file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/2l2f.A.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

# Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Set the background color to grey
ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

# Create a custom normalization centered around zero using TwoSlopeNorm
vmin = np.min(first_values)
vmax = np.max(first_values)
abs_max = np.max([np.abs(vmin), np.abs(vmax)])
norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

# Scatter plot with colors representing the first values
sc = ax.scatter(
    x_coords, y_coords, z_coords, 
    c=first_values, 
    cmap='seismic', 
    norm=norm,
    marker='o', 
    s=1
)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

# Remove ticks from the plot
ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = '2l2f.A.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [ ]:
import pickle

# Define the path to the file
file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/3mvg.A.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

# Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Set the background color to grey
ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

# Create a custom normalization centered around zero using TwoSlopeNorm
vmin = np.min(first_values)
vmax = np.max(first_values)
abs_max = np.max([np.abs(vmin), np.abs(vmax)])
norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

# Scatter plot with colors representing the first values
sc = ax.scatter(
    x_coords, y_coords, z_coords, 
    c=first_values, 
    cmap='seismic', 
    norm=norm,
    marker='o', 
    s=1
)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

# Remove ticks from the plot
ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = '3mvg.A.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

### Very large afdb2000 protein bad cases (+ig)

AF-A0A131MBU3-F1-model_v4

AF-A0A0M4L8I7-F1-model_v4

In [26]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

In [27]:
data[data['Sequence_Length'] > 2000]

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,Sequence_Length,Contact_Order,Title
219,0.153360,0.276951,0.164429,0.128608,51.318896,0.1486,0.150350,0.181395,2217,0.015562,AF-A0A131MBU3-F1-model_v4
329,0.190782,0.307816,0.164401,0.151530,47.501242,0.1492,0.188864,0.208000,2495,0.016072,AF-A0A1Y0BRF1-F1-model_v4
446,0.158157,0.272937,0.162399,0.142025,65.931805,0.1233,0.154440,0.189781,2605,0.018915,AF-A0A3G1DJH7-F1-model_v4
699,0.165921,0.284489,0.162263,0.144297,49.798240,0.1617,0.168374,0.141079,2682,0.015921,AF-A0A4P8GHJ1-F1-model_v4
881,0.172063,0.292322,0.164237,0.136296,49.741359,0.1710,0.168551,0.203704,2162,0.019126,AF-A0A2U8NET4-F1-model_v4
1203,0.156988,0.289948,0.163308,0.141674,68.233201,0.1298,0.152778,0.192453,2497,0.019423,AF-A0A0M4L8I7-F1-model_v4

#### ig

In [ ]:
import pickle

# Define the path to the file
file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/AF-A0A131MBU3-F1-model_v4.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

# Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Set the background color to grey
ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

# Create a custom normalization centered around zero using TwoSlopeNorm
vmin = np.min(first_values)
vmax = np.max(first_values)
abs_max = np.max([np.abs(vmin), np.abs(vmax)])
norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

# Scatter plot with colors representing the first values
sc = ax.scatter(
    x_coords, y_coords, z_coords, 
    c=first_values, 
    cmap='seismic', 
    norm=norm,
    marker='o', 
    s=1
)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

# Remove ticks from the plot
ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = 'AF-A0A131MBU3-F1-model_v4.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [ ]:
import pickle

# Define the path to the file
file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/AF-A0A0M4L8I7-F1-model_v4.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm

# Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Set the background color to grey
ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

# Create a custom normalization centered around zero using TwoSlopeNorm
vmin = np.min(first_values)
vmax = np.max(first_values)
abs_max = np.max([np.abs(vmin), np.abs(vmax)])
norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

# Scatter plot with colors representing the first values
sc = ax.scatter(
    x_coords, y_coords, z_coords, 
    c=first_values, 
    cmap='seismic', 
    norm=norm,
    marker='o', 
    s=1
)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

# Remove ticks from the plot
ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = 'AF-A0A0M4L8I7-F1-model_v4.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))

In [10]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

def draw_afdb2000_ig(title):
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
    surface_coords = data['surface']         # Shape (n, 3)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Extract the coordinates of each point
    x_coords = surface_coords[:, 0]
    y_coords = surface_coords[:, 1]
    z_coords = surface_coords[:, 2]

    # Create a 3D scatter plot
    fig = plt.figure(figsize=(7, 5))
    ax = fig.add_subplot(111, projection='3d')

    # Set the background color to grey
    ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

    # Create a custom normalization centered around zero using TwoSlopeNorm
    # vmin = np.min(first_values)
    # vmax = np.max(first_values)
    vmin = np.percentile(first_values, 1)  # 10th percentile
    vmax = np.percentile(first_values, 99)  # 90th percentile
    abs_max = np.max([np.abs(vmin), np.abs(vmax)])
    norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

    # Scatter plot with colors representing the first values
    sc = ax.scatter(
        x_coords, y_coords, z_coords, 
        c=first_values, 
        cmap='seismic', 
        norm=norm,
        marker='o', 
        s=1
    )

    # Add color bar to indicate value distribution
    cbar = plt.colorbar(sc, ax=ax)
    # cbar.set_label('First Value of grads_A (white represents neutral)')

    # Reduce the size of the color bar
    cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

    # Remove ticks from the plot
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])

    ax.set_axis_off()

    # Set the elevation to 0
    ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

    # Show plot
    # plt.show()
    # Path to save the figure
    save_path = './figures/ig/very_large_AFDB2000_cases_99percentile'
    file_name = f'{title}.png'

    # Create the directory if it doesn't exist
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    plt.savefig(os.path.join(save_path, file_name))
    plt.close(fig)


titles = ['AF-A0A131MBU3-F1-model_v4', 'AF-A0A0M4L8I7-F1-model_v4']
for title in titles:
    draw_afdb2000_ig(title)

### good afdb2000 protein good cases (+ig)
AF-A1JPL9-F1-model_v4

In [8]:
import pandas as pd

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

In [22]:
data[(data['Recovery'] > 0.98) & (data['TMScore'] > 0.99)]

,Recovery,NSSR,pLDDT_CA,pLDDT,RMSD,TMScore,Surface Recovery,Core Recovery,Sequence_Length,Contact_Order,Title
378,0.980080,1.0,0.971155,0.952144,0.502831,0.9939,0.979798,0.981132,251,0.091214,AF-A0QEZ8-F1-model_v4
1859,0.983871,1.0,0.977581,0.959947,0.410790,0.9954,0.989474,0.965517,248,0.087702,AF-A1UIA4-F1-model_v4

In [23]:
# data[data['Recovery'] > 0.99]['Title'].tolist()
data[(data['Recovery'] > 0.98) & (data['TMScore'] > 0.99)]['Title'].tolist()

['AF-A0QEZ8-F1-model_v4', 'AF-A1UIA4-F1-model_v4']

#### ig

In [11]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

def draw_afdb2000_ig(title):
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
    surface_coords = data['surface']         # Shape (n, 3)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Extract the coordinates of each point
    x_coords = surface_coords[:, 0]
    y_coords = surface_coords[:, 1]
    z_coords = surface_coords[:, 2]

    # Create a 3D scatter plot
    fig = plt.figure(figsize=(7, 5))
    ax = fig.add_subplot(111, projection='3d')

    # Set the background color to grey
    ax.set_facecolor('#d3d3d3')  # Set the 3D axis background to grey

    # Create a custom normalization centered around zero using TwoSlopeNorm
    # vmin = np.min(first_values)
    # vmax = np.max(first_values)
    vmin = np.percentile(first_values, 1)  # 10th percentile
    vmax = np.percentile(first_values, 99)  # 90th percentile
    abs_max = np.max([np.abs(vmin), np.abs(vmax)])
    norm = TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

    # Scatter plot with colors representing the first values
    sc = ax.scatter(
        x_coords, y_coords, z_coords, 
        c=first_values, 
        cmap='seismic', 
        norm=norm,
        marker='o', 
        s=1
    )

    # Add color bar to indicate value distribution
    cbar = plt.colorbar(sc, ax=ax)
    # cbar.set_label('First Value of grads_A (white represents neutral)')

    # Reduce the size of the color bar
    cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

    # Remove ticks from the plot
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])

    ax.set_axis_off()

    # Set the elevation to 0
    ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

    # Show plot
    # plt.show()
    # Path to save the figure
    save_path = './figures/ig/small_AFDB2000_cases_99percentile'
    file_name = f'{title}.png'

    # Create the directory if it doesn't exist
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    plt.savefig(os.path.join(save_path, file_name))
    plt.close(fig)


titles = ['AF-A1JPL9-F1-model_v4']
for title in titles:
    draw_afdb2000_ig(title)

### afdb2000 protein cases

#### ig

##### hydro

In [22]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

def draw_afdb2000_ig(title, universal_abs_max):
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    # Extracting the relevant data
    grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
    surface_coords = data['surface']         # Shape (n, 3)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Extract the coordinates of each point
    x_coords = surface_coords[:, 0]
    y_coords = surface_coords[:, 1]
    z_coords = surface_coords[:, 2]

    # Create a 3D scatter plot
    fig = plt.figure(figsize=(5, 5))
    ax = fig.add_subplot(111, projection='3d')

    # Set the background color to grey
    ax.set_facecolor('#f3f3f3')  # Set the 3D axis background to grey

    # Create a custom normalization centered around zero using TwoSlopeNorm
    norm = TwoSlopeNorm(vmin=-universal_abs_max, vcenter=0, vmax=universal_abs_max)

    # Scatter plot with colors representing the first values
    sc = ax.scatter(
        x_coords, y_coords, z_coords, 
        c=first_values, 
        cmap='seismic', 
        norm=norm,
        marker='o', 
        s=1
    )

    # # Add color bar to indicate value distribution
    # cbar = plt.colorbar(sc, ax=ax)

    # # Reduce the size of the color bar
    # cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

    # Remove ticks from the plot
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])

    ax.set_axis_off()

    # Set the elevation to 0
    ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

    # Path to save the figure
    save_path = './figures/ig/hydro_AFDB2000_cases_99percentile'
    file_name = f'{title}.png'

    # Create the directory if it doesn't exist
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    plt.savefig(os.path.join(save_path, file_name))
    plt.close(fig)

def find_max_abs_max(titles):
    max_abs_max = 0
    max_title = None
    for title in titles:
        # Define the path to the file
        file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

        # Open the file in read-binary mode and load it using pickle
        with open(file_path, 'rb') as file:
            data = pickle.load(file)

        # Extracting the relevant data
        grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)

        # Extract the first values of each point
        first_values = grads_A[:, 0]  # This is an array of shape (n,)

        # Calculate percentiles and abs_max
        vmin = np.percentile(first_values, 1)
        vmax = np.percentile(first_values, 99)
        abs_max = np.max([np.abs(vmin), np.abs(vmax)])

        # Update the max_abs_max if current abs_max is greater
        if abs_max > max_abs_max:
            max_abs_max = abs_max
            max_title = title

    print(f'The maximum abs_max value is {max_abs_max}, provided by {max_title}')
    return max_abs_max

# Lists of good and bad cases
# good_cases = ['AF-A2C404-F1-model_v4',
#               'AF-A0T0C4-F1-model_v4',
#               'AF-A2RNN0-F1-model_v4',
#               'AF-A1EA42-F1-model_v4',
#               'AF-A0T0S5-F1-model_v4',
#               'AF-A1JS06-F1-model_v4',
#               'AF-A1JPL9-F1-model_v4',
#               'AF-A1E9I0-F1-model_v4',
#               'AF-A0LV84-F1-model_v4']
# good_cases = ['AF-A0QEZ8-F1-model_v4', 'AF-A1UIA4-F1-model_v4']
# bad_cases = ['AF-A0A131MBU3-F1-model_v4', 'AF-A0A0M4L8I7-F1-model_v4']

good_cases = ['AF-A0QEZ8-F1-model_v4']
bad_cases = ['AF-A0A131MBU3-F1-model_v4']

# Find the maximum abs_max across all cases
all_cases = good_cases + bad_cases
universal_abs_max = find_max_abs_max(all_cases)

# Generate plots using the universal abs_max
for title in good_cases:
    draw_afdb2000_ig(title, universal_abs_max)

for title in bad_cases:
    draw_afdb2000_ig(title, universal_abs_max)

The maximum abs_max value is 0.36748653650283813, provided by AF-A0QEZ8-F1-model_v4

##### charge

In [25]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import TwoSlopeNorm
import os

def draw_afdb2000_ig(title, universal_abs_max):
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    # Extracting the relevant data
    grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)
    surface_coords = data['surface']         # Shape (n, 3)

    # Extract the first values of each point
    first_values = grads_A[:, 1]  # This is an array of shape (n,)

    # Extract the coordinates of each point
    x_coords = surface_coords[:, 0]
    y_coords = surface_coords[:, 1]
    z_coords = surface_coords[:, 2]

    # Create a 3D scatter plot
    fig = plt.figure(figsize=(5, 5))
    ax = fig.add_subplot(111, projection='3d')

    # Set the background color to grey
    ax.set_facecolor('#f3f3f3')  # Set the 3D axis background to grey

    # Create a custom normalization centered around zero using TwoSlopeNorm
    norm = TwoSlopeNorm(vmin=-universal_abs_max, vcenter=0, vmax=universal_abs_max)

    # Scatter plot with colors representing the first values
    sc = ax.scatter(
        x_coords, y_coords, z_coords, 
        c=first_values, 
        cmap='seismic', 
        norm=norm,
        marker='o', 
        s=1
    )

    # # Add color bar to indicate value distribution
    # cbar = plt.colorbar(sc, ax=ax)

    # # Reduce the size of the color bar
    # cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]

    # Remove ticks from the plot
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])

    ax.set_axis_off()

    # Set the elevation to 0
    ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

    # Path to save the figure
    save_path = './figures/ig/charge_AFDB2000_cases_99percentile'
    file_name = f'{title}.png'

    # Create the directory if it doesn't exist
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    plt.savefig(os.path.join(save_path, file_name))
    plt.close(fig)

def find_max_abs_max(titles):
    max_abs_max = 0
    max_title = None
    for title in titles:
        # Define the path to the file
        file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

        # Open the file in read-binary mode and load it using pickle
        with open(file_path, 'rb') as file:
            data = pickle.load(file)

        # Extracting the relevant data
        grads_A = data['grads']['biochem']['overall']  # Shape (n, 2)

        # Extract the first values of each point
        first_values = grads_A[:, 1]  # This is an array of shape (n,)

        # Calculate percentiles and abs_max
        vmin = np.percentile(first_values, 1)
        vmax = np.percentile(first_values, 99)
        abs_max = np.max([np.abs(vmin), np.abs(vmax)])

        # Update the max_abs_max if current abs_max is greater
        if abs_max > max_abs_max:
            max_abs_max = abs_max
            max_title = title

    print(f'The maximum abs_max value is {max_abs_max}, provided by {max_title}')
    return max_abs_max

# Lists of good and bad cases
# good_cases = ['AF-A2C404-F1-model_v4',
#               'AF-A0T0C4-F1-model_v4',
#               'AF-A2RNN0-F1-model_v4',
#               'AF-A1EA42-F1-model_v4',
#               'AF-A0T0S5-F1-model_v4',
#               'AF-A1JS06-F1-model_v4',
#               'AF-A1JPL9-F1-model_v4',
#               'AF-A1E9I0-F1-model_v4',
#               'AF-A0LV84-F1-model_v4']
# good_cases = ['AF-A0QEZ8-F1-model_v4', 'AF-A1UIA4-F1-model_v4']
# bad_cases = ['AF-A0A131MBU3-F1-model_v4', 'AF-A0A0M4L8I7-F1-model_v4']
good_cases = ['AF-A0QEZ8-F1-model_v4']
bad_cases = ['AF-A0A131MBU3-F1-model_v4']

# Find the maximum abs_max across all cases
# all_cases = good_cases + bad_cases
# universal_abs_max = find_max_abs_max(all_cases)

# Generate plots using the universal abs_max
for title in good_cases:
    draw_afdb2000_ig(title, universal_abs_max)

for title in bad_cases:
    draw_afdb2000_ig(title, universal_abs_max)

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

universal_abs_max = 0.36748653650283813

# Create a figure and axis for the colorbar
fig, ax = plt.subplots(figsize=(0.5, 6))

# Create a colormap normalization based on the range [-universal_abs_max, universal_abs_max]
norm = mpl.colors.Normalize(vmin=-universal_abs_max, vmax=universal_abs_max)

# Create a colorbar with the 'seismic' colormap
cbar = mpl.colorbar.ColorbarBase(ax, cmap='seismic', norm=norm, orientation='vertical')

# Set colorbar label and ticks
cbar.set_label('IG')
ticks = [-universal_abs_max, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, universal_abs_max]

# Set colorbar ticks and format them to one digit after the decimal
cbar.set_ticks(ticks)
cbar.ax.set_yticklabels([f'{tick:.2f}' for tick in ticks])

# Show the colorbar
# plt.show()
# Path to save the figure
save_path = './figures/ig/charge_AFDB2000_cases_99percentile'
file_name = f'legend.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

## ig

#### ig-recovery relationship

##### single LOWESS

In [4]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']  # Shape (n, 2)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title
    recovery = data[data['Title'] == title]['Recovery'].values[0]
    recoverys.append(recovery)

# Create a scatter plot
fig = plt.figure(figsize=(10, 6))
plt.scatter(igs, recoverys, color='blue', alpha=0.6, label='Data Points')

# Fit a LOWESS curve to the data
lowess = sm.nonparametric.lowess(recoverys, igs, frac=0.3)
plt.plot(lowess[:, 0], lowess[:, 1], color='red', label='LOWESS Fit')

# Set plot labels and title
plt.xlabel('Hydrophobicity IG (Integrated Gradient Mean)')
plt.ylabel('Recovery')
# plt.title('Scatter Plot of Recovery vs IG with LOWESS Fit')
plt.legend()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = f'hydro_ig_recovery.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [ ]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']  # Shape (n, 2)

    # Extract the first values of each point
    first_values = grads_A[:, 1]  # This is an array of shape (n,)

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title
    recovery = data[data['Title'] == title]['Recovery'].values[0]
    recoverys.append(recovery)

# Create a scatter plot
fig = plt.figure(figsize=(10, 6))
plt.scatter(igs, recoverys, color='blue', alpha=0.6, label='Data Points')

# Fit a LOWESS curve to the data
lowess = sm.nonparametric.lowess(recoverys, igs, frac=0.3)
plt.plot(lowess[:, 0], lowess[:, 1], color='red', label='LOWESS Fit')

# Set plot labels and title
plt.xlabel('Charge IG (Integrated Gradient Mean)')
plt.ylabel('Recovery')
# plt.title('Scatter Plot of Recovery vs IG with LOWESS Fit')
plt.legend()

# Show the plot
# plt.show()
# Path to save the figure
save_path = './figures/ig'
file_name = f'charge_ig_recovery.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

##### split LOWESS fit

In [12]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']

    # Extract the first values of each point
    first_values = grads_A[:, 0]

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title and multiply by 100
    recovery = data[data['Title'] == title]['Recovery'].values[0] * 100
    recoverys.append(recovery)

# Convert lists to numpy arrays
igs = np.array(igs)
recoverys = np.array(recoverys)

# Split data into two groups based on recovery threshold
threshold = 70  # Adjusted to match the scaling by 100
igs_high = igs[recoverys > threshold]
recoverys_high = recoverys[recoverys > threshold]
igs_low = igs[recoverys <= threshold]
recoverys_low = recoverys[recoverys <= threshold]

# Create a hexbin plot with enhanced color for low count regions
# fig = plt.figure(figsize=(10, 6))
fig, ax = plt.subplots(figsize=(10, 6))
# plt.hexbin(igs, recoverys, gridsize=50, cmap='cividis', mincnt=1, reduce_C_function=np.sum)
hb = plt.hexbin(igs, recoverys, gridsize=50, cmap='cividis', mincnt=1, reduce_C_function=np.sum)

# # Add colorbar as a legend for the hex plot
# cb = plt.colorbar(hb)
# cb.set_label('Counts')
# Add colorbar inside the plot
cb = plt.colorbar(hb, ax=ax, orientation='vertical', shrink=0.8, pad=0.05)
cb.set_label('Counts')

# Fit LOWESS curves to the high and low recovery data
lowess_high = sm.nonparametric.lowess(recoverys_high, igs_high, frac=0.3)
lowess_low = sm.nonparametric.lowess(recoverys_low, igs_low, frac=0.3)

# Define new contrasting colors for the LOWESS fit and CI
color_high = 'crimson'  # Changed to reddish color for high fit
color_low = 'teal'

# Plot the LOWESS fits with the new reddish color for the high recovery fit
plt.plot(lowess_high[:, 0], lowess_high[:, 1], color=color_high, label='LOWESS Fit (High Recovery)', zorder=5)
plt.plot(lowess_low[:, 0], lowess_low[:, 1], color=color_low, label='LOWESS Fit (Low Recovery)', zorder=5)

# Bootstrap 95% confidence intervals for LOWESS fit
def bootstrap_lowess(x, y, frac=0.3, n_bootstrap=1000, ci=95):
    lowess_bootstraps = []
    for _ in range(n_bootstrap):
        indices = np.random.choice(range(len(x)), size=len(x), replace=True)
        lowess_fit = sm.nonparametric.lowess(y[indices], x[indices], frac=frac)
        lowess_bootstraps.append(lowess_fit[:, 1])
    lowess_bootstraps = np.array(lowess_bootstraps)
    lower_bound = np.percentile(lowess_bootstraps, (100 - ci) / 2, axis=0)
    upper_bound = np.percentile(lowess_bootstraps, 100 - (100 - ci) / 2, axis=0)
    return lower_bound, upper_bound

# Add bootstrap 95% CI for LOWESS fits with increased alpha
lowess_high_lower, lowess_high_upper = bootstrap_lowess(igs_high, recoverys_high)
lowess_low_lower, lowess_low_upper = bootstrap_lowess(igs_low, recoverys_low)

# Plot shaded region for 95% CI with new colors and higher alpha for visibility
plt.fill_between(lowess_high[:, 0], lowess_high_lower, lowess_high_upper, color=color_high, alpha=0.5, label='95% CI (High Recovery)')
plt.fill_between(lowess_low[:, 0], lowess_low_lower, lowess_low_upper, color=color_low, alpha=0.5, label='95% CI (Low Recovery)')

# Calculate R-squared for high and low recovery groups
def calculate_r_squared(x, y, slope, intercept):
    # Calculate predicted values from the linear fit
    y_pred = slope * x + intercept
    # Calculate total sum of squares (SST) and residual sum of squares (SSR)
    ss_tot = np.sum((y - np.mean(y))**2)
    ss_res = np.sum((y - y_pred)**2)
    # Calculate R-squared
    r_squared = 1 - (ss_res / ss_tot)
    return r_squared

# Fit linear models for the two groups
slope_high, intercept_high = np.polyfit(igs_high, recoverys_high, 1)
slope_low, intercept_low = np.polyfit(igs_low, recoverys_low, 1)

# Calculate R-squared for both groups
r_squared_high = calculate_r_squared(igs_high, recoverys_high, slope_high, intercept_high)
r_squared_low = calculate_r_squared(igs_low, recoverys_low, slope_low, intercept_low)

# Modify the legend to include the R-squared values
legend_label_high = f'Linear Fit (High Recovery) $R^2$={r_squared_high:.3f}'
legend_label_low = f'Linear Fit (Low Recovery) $R^2$={r_squared_low:.3f}'

# Plot the linear fits with the new colors
plt.plot(igs_high, slope_high * igs_high + intercept_high, color=color_high, linestyle='--', label=legend_label_high, zorder=6)
plt.plot(igs_low, slope_low * igs_low + intercept_low, color=color_low, linestyle='--', label=legend_label_low, zorder=6)

# Add dotted lines at y=60 and y=80 (without labels)
plt.axhline(y=60, color='black', linestyle='--', linewidth=1, zorder=4)
plt.axhline(y=80, color='black', linestyle='--', linewidth=1, zorder=4)

# Add dotted vertical lines at min x of high recovery and max x of low recovery (without labels)
plt.axvline(x=min(igs_high), color='black', linestyle='--', linewidth=1, zorder=4)
plt.axvline(x=max(igs_low), color='black', linestyle='--', linewidth=1, zorder=4)

# Set y-axis limits to (0, 100)
plt.ylim(0, 100)

# Add grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Set plot labels
plt.xlabel('Hydrophobicity IG')
plt.ylabel('Sequence Recovery (%)')

# Add legend
plt.legend()

# Save the plot
save_path = './figures/ig'
file_name = f'hydro_ig_recovery_lowess_split.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [13]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import matplotlib.pyplot as plt
import os

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']

    # Extract the first values of each point
    first_values = grads_A[:, 1]

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title and multiply by 100
    recovery = data[data['Title'] == title]['Recovery'].values[0] * 100
    recoverys.append(recovery)

# Convert lists to numpy arrays
igs = np.array(igs)
recoverys = np.array(recoverys)

# Split data into two groups based on recovery threshold
threshold = 70  # Adjusted to match the scaling by 100
igs_high = igs[recoverys > threshold]
recoverys_high = recoverys[recoverys > threshold]
igs_low = igs[recoverys <= threshold]
recoverys_low = recoverys[recoverys <= threshold]

# Create a hexbin plot with enhanced color for low count regions
# fig = plt.figure(figsize=(10, 6))
fig, ax = plt.subplots(figsize=(10, 6))
# plt.hexbin(igs, recoverys, gridsize=50, cmap='cividis', mincnt=1, reduce_C_function=np.sum)
hb = plt.hexbin(igs, recoverys, gridsize=50, cmap='cividis', mincnt=1, reduce_C_function=np.sum)

# # Add colorbar as a legend for the hex plot
# cb = plt.colorbar(hb)
# cb.set_label('Counts')
# Add colorbar inside the plot
cb = plt.colorbar(hb, ax=ax, orientation='vertical', shrink=0.8, pad=0.05)
cb.set_label('Counts')

# Fit LOWESS curves to the high and low recovery data
lowess_high = sm.nonparametric.lowess(recoverys_high, igs_high, frac=0.3)
lowess_low = sm.nonparametric.lowess(recoverys_low, igs_low, frac=0.3)

# Define new contrasting colors for the LOWESS fit and CI
color_high = 'crimson'  # Changed to reddish color for high fit
color_low = 'teal'

# Plot the LOWESS fits with the new reddish color for the high recovery fit
plt.plot(lowess_high[:, 0], lowess_high[:, 1], color=color_high, label='LOWESS Fit (High Recovery)', zorder=5)
plt.plot(lowess_low[:, 0], lowess_low[:, 1], color=color_low, label='LOWESS Fit (Low Recovery)', zorder=5)

# Bootstrap 95% confidence intervals for LOWESS fit
def bootstrap_lowess(x, y, frac=0.3, n_bootstrap=1000, ci=95):
    lowess_bootstraps = []
    for _ in range(n_bootstrap):
        indices = np.random.choice(range(len(x)), size=len(x), replace=True)
        lowess_fit = sm.nonparametric.lowess(y[indices], x[indices], frac=frac)
        lowess_bootstraps.append(lowess_fit[:, 1])
    lowess_bootstraps = np.array(lowess_bootstraps)
    lower_bound = np.percentile(lowess_bootstraps, (100 - ci) / 2, axis=0)
    upper_bound = np.percentile(lowess_bootstraps, 100 - (100 - ci) / 2, axis=0)
    return lower_bound, upper_bound

# Add bootstrap 95% CI for LOWESS fits with increased alpha
lowess_high_lower, lowess_high_upper = bootstrap_lowess(igs_high, recoverys_high)
lowess_low_lower, lowess_low_upper = bootstrap_lowess(igs_low, recoverys_low)

# Plot shaded region for 95% CI with new colors and higher alpha for visibility
plt.fill_between(lowess_high[:, 0], lowess_high_lower, lowess_high_upper, color=color_high, alpha=0.5, label='95% CI (High Recovery)')
plt.fill_between(lowess_low[:, 0], lowess_low_lower, lowess_low_upper, color=color_low, alpha=0.5, label='95% CI (Low Recovery)')

# Calculate R-squared for high and low recovery groups
def calculate_r_squared(x, y, slope, intercept):
    # Calculate predicted values from the linear fit
    y_pred = slope * x + intercept
    # Calculate total sum of squares (SST) and residual sum of squares (SSR)
    ss_tot = np.sum((y - np.mean(y))**2)
    ss_res = np.sum((y - y_pred)**2)
    # Calculate R-squared
    r_squared = 1 - (ss_res / ss_tot)
    return r_squared

# Fit linear models for the two groups
slope_high, intercept_high = np.polyfit(igs_high, recoverys_high, 1)
slope_low, intercept_low = np.polyfit(igs_low, recoverys_low, 1)

# Calculate R-squared for both groups
r_squared_high = calculate_r_squared(igs_high, recoverys_high, slope_high, intercept_high)
r_squared_low = calculate_r_squared(igs_low, recoverys_low, slope_low, intercept_low)

# Modify the legend to include the R-squared values
legend_label_high = f'Linear Fit (High Recovery) $R^2$={r_squared_high:.3f}'
legend_label_low = f'Linear Fit (Low Recovery) $R^2$={r_squared_low:.3f}'

# Plot the linear fits with the new colors
plt.plot(igs_high, slope_high * igs_high + intercept_high, color=color_high, linestyle='--', label=legend_label_high, zorder=6)
plt.plot(igs_low, slope_low * igs_low + intercept_low, color=color_low, linestyle='--', label=legend_label_low, zorder=6)

# Add dotted lines at y=60 and y=80 (without labels)
plt.axhline(y=60, color='black', linestyle='--', linewidth=1, zorder=4)
plt.axhline(y=80, color='black', linestyle='--', linewidth=1, zorder=4)

# Add dotted vertical lines at min x of high recovery and max x of low recovery (without labels)
plt.axvline(x=min(igs_high), color='black', linestyle='--', linewidth=1, zorder=4)
plt.axvline(x=max(igs_low), color='black', linestyle='--', linewidth=1, zorder=4)

# Set y-axis limits to (0, 100)
plt.ylim(0, 100)

# Add grid
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.7)

# Set plot labels
plt.xlabel('Charge IG')
plt.ylabel('Sequence Recovery (%)')

# Add legend
plt.legend()

# Save the plot
save_path = './figures/ig'
file_name = f'charge_ig_recovery_lowess_split.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Save the plot
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

##### two linear fit

In [3]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import os
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import scipy.stats as stats

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']  # Shape (n, 2)

    # Extract the first values of each point
    first_values = grads_A[:, 0]  # This is an array of shape (n,)

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title
    recovery = data[data['Title'] == title]['Recovery'].values[0]
    recoverys.append(recovery)

# Convert lists to numpy arrays
igs = np.array(igs)
recoverys = np.array(recoverys)

# Split data into two groups based on recovery threshold
threshold = 0.7
igs_high = igs[recoverys > threshold]
recoverys_high = recoverys[recoverys > threshold]
igs_low = igs[recoverys <= threshold]
recoverys_low = recoverys[recoverys <= threshold]

# Perform linear regression for recovery > 0.7
model_high = LinearRegression()
model_high.fit(igs_high.reshape(-1, 1), recoverys_high)

# Calculate statistics for high recovery group
r2_high = r2_score(recoverys_high, model_high.predict(igs_high.reshape(-1, 1)))
mse_high = mean_squared_error(recoverys_high, model_high.predict(igs_high.reshape(-1, 1)))

# Calculate significance of the slope for high recovery group
slope, intercept, r_value, p_value, std_err = stats.linregress(igs_high, recoverys_high)

# Display the regression formula and statistics for high recovery group
print(f"High Recovery Group: y = {model_high.coef_[0]:.4f} * x + {model_high.intercept_:.4f}")
print(f"R^2: {r2_high:.4f}")
print(f"MSE: {mse_high:.4f}")
print(f"p-value for slope: {p_value:.4e}\n")

# Perform linear regression for recovery <= 0.7
model_low = LinearRegression()
model_low.fit(igs_low.reshape(-1, 1), recoverys_low)

# Calculate statistics for low recovery group
r2_low = r2_score(recoverys_low, model_low.predict(igs_low.reshape(-1, 1)))
mse_low = mean_squared_error(recoverys_low, model_low.predict(igs_low.reshape(-1, 1)))

# Calculate significance of the slope for low recovery group
slope, intercept, r_value, p_value, std_err = stats.linregress(igs_low, recoverys_low)

# Display the regression formula and statistics for low recovery group
print(f"Low Recovery Group: y = {model_low.coef_[0]:.4f} * x + {model_low.intercept_:.4f}")
print(f"R^2: {r2_low:.4f}")
print(f"MSE: {mse_low:.4f}")
print(f"p-value for slope: {p_value:.4e}\n")

High Recovery Group: y = 0.8354 * x + 0.9103
R^2: 0.0457
MSE: 0.0005
p-value for slope: 3.6702e-16

Low Recovery Group: y = 17.3675 * x + -0.0884
R^2: 0.3330
MSE: 0.0080
p-value for slope: 1.5531e-52

In [7]:
import pandas as pd
import statsmodels.api as sm
import pickle
import numpy as np
import os
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import scipy.stats as stats

# Specify the path to the CSV file
file_path = './test_results/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/test_results.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Initialize lists to store ig and recovery values
igs = []
recoverys = []

for title in data['Title']:
    # Define the path to the file
    file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/AFDB2000/{title}.pkl'

    # Open the file in read-binary mode and load it using pickle
    with open(file_path, 'rb') as file:
        ig_data = pickle.load(file)

    # Assuming data is already loaded, and data['grads']['biochem']['R'] and data['surface'] are available
    # Extracting the relevant data
    grads_A = ig_data['grads']['biochem']['overall']  # Shape (n, 2)

    # Extract the first values of each point
    first_values = grads_A[:, 1]  # This is an array of shape (n,)

    # Compute the mean of the first values
    ig = np.abs(first_values).mean()
    igs.append(ig)

    # Extract the recovery value corresponding to the title
    recovery = data[data['Title'] == title]['Recovery'].values[0]
    recoverys.append(recovery)

# Convert lists to numpy arrays
igs = np.array(igs)
recoverys = np.array(recoverys)

# Split data into two groups based on recovery threshold
threshold = 0.7
igs_high = igs[recoverys > threshold]
recoverys_high = recoverys[recoverys > threshold]
igs_low = igs[recoverys <= threshold]
recoverys_low = recoverys[recoverys <= threshold]

# Perform linear regression for recovery > 0.7
model_high = LinearRegression()
model_high.fit(igs_high.reshape(-1, 1), recoverys_high)

# Calculate statistics for high recovery group
r2_high = r2_score(recoverys_high, model_high.predict(igs_high.reshape(-1, 1)))
mse_high = mean_squared_error(recoverys_high, model_high.predict(igs_high.reshape(-1, 1)))

# Calculate significance of the slope for high recovery group
slope, intercept, r_value, p_value, std_err = stats.linregress(igs_high, recoverys_high)

# Display the regression formula and statistics for high recovery group
print(f"High Recovery Group: y = {model_high.coef_[0]:.4f} * x + {model_high.intercept_:.4f}")
print(f"R^2: {r2_high:.4f}")
print(f"MSE: {mse_high:.4f}")
print(f"p-value for slope: {p_value:.4e}\n")

# Perform linear regression for recovery <= 0.7
model_low = LinearRegression()
model_low.fit(igs_low.reshape(-1, 1), recoverys_low)

# Calculate statistics for low recovery group
r2_low = r2_score(recoverys_low, model_low.predict(igs_low.reshape(-1, 1)))
mse_low = mean_squared_error(recoverys_low, model_low.predict(igs_low.reshape(-1, 1)))

# Calculate significance of the slope for low recovery group
slope, intercept, r_value, p_value, std_err = stats.linregress(igs_low, recoverys_low)

# Display the regression formula and statistics for low recovery group
print(f"Low Recovery Group: y = {model_low.coef_[0]:.4f} * x + {model_low.intercept_:.4f}")
print(f"R^2: {r2_low:.4f}")
print(f"MSE: {mse_low:.4f}")
print(f"p-value for slope: {p_value:.4e}\n")

High Recovery Group: y = 0.7215 * x + 0.9221
R^2: 0.0139
MSE: 0.0005
p-value for slope: 8.4088e-06

Low Recovery Group: y = 21.5063 * x + -0.0584
R^2: 0.3109
MSE: 0.0082
p-value for slope: 1.9397e-48

#### try code

In [ ]:
import pickle

# Define the path to the file
# file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/1a1x.A.pkl'
file_path = './ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/1y66.A.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

data

In [ ]:
data.keys()

In [ ]:
# Assume 'data' is the dictionary you've loaded using pickle
def print_dict_structure(d, indent=0):
    spacing = '  ' * indent
    if isinstance(d, dict):
        for key, value in d.items():
            if isinstance(value, dict):
                print(f"{spacing}{key}: dict")
                print_dict_structure(value, indent + 1)
            elif isinstance(value, list):
                print(f"{spacing}{key}: list (length: {len(value)})")
                if len(value) > 0 and isinstance(value[0], dict):
                    print(f"{spacing}  [list of dicts]")
            else:
                print(f"{spacing}{key}: {type(value).__name__}")
    else:
        print(f"{spacing}{type(d).__name__}")

# Run the function
print_dict_structure(data)

In [ ]:
data['grads']['biochem']['A'].shape

In [ ]:
data['surface'].shape

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['A']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['R']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['A']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 1]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads = data['grads']['biochem']['overall']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads[:, 1]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['R']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
cbar.set_label('First Value of grads_A (white represents neutral)')

# Set labels for better understanding
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')
ax.set_title('3D Visualization of Point Cloud with First Values Color-Coded')

# Set the elevation to 0
ax.view_init(elev=0, azim=0)  # Elevation is set to 0 degrees

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['R']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]


# Remove ticks from the plot
ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
plt.show()

In [73]:
import pickle

# title = '1y66.A'
title = '4bw5.C'
# Define the path to the file
file_path = f'./ig_biochem_results_steps50/SBC2-sum3-minlrdiv1-bs4-lr00002-epoch20-test/CATH4.2SurfProPiFoldDense/{title}.pkl'

# Open the file in read-binary mode and load it using pickle
with open(file_path, 'rb') as file:
    data = pickle.load(file)

surface_path = './data/cath4.2surfpropifold-dense/cath42_pc_test.pkl'
with open(surface_path, 'rb') as f:
    test_dict = pickle.load(f)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['R']  # Shape (n, 2)
surface_coords = data['surface']         # Shape (n, 3)
# surface_coords = test_dict[title]['surface']

# 定义旋转角度（以弧度表示）
theta = np.radians(90)  # 例如旋转45度

# 定义旋转轴，沿着 x = y 轴的方向向量
axis = np.array([1, 1, 0])
axis = axis / np.linalg.norm(axis)  # 单位化

# Rodrigues 旋转公式实现
def rotate_point_cloud(point_cloud, axis, theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    R = (cos_theta * np.eye(3) + 
         sin_theta * np.array([[0, -axis[2], axis[1]],
                               [axis[2], 0, -axis[0]],
                               [-axis[1], axis[0], 0]]) +
         (1 - cos_theta) * np.outer(axis, axis))
    
    return np.dot(point_cloud, R.T)

# 执行旋转
# surface_coords = rotate_point_cloud(surface_coords, axis, theta)
# surface_coords = rotate_point_cloud(surface_coords, np.array([-1, 1, 0]) / np.linalg.norm(np.array([-1, 1, 0])), np.radians(90))
# surface_coords = rotate_point_cloud(surface_coords, np.array([0, 0, 1]), np.radians(45))
# surface_coords = rotate_point_cloud(surface_coords, np.array([1, 0, 0]), np.radians(90))

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]


# Remove ticks from the plot
# ax.set_xticks([])
# ax.set_yticks([])
# ax.set_zticks([])

ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')

# ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assume data is already loaded, and data['grads']['biochem']['A'] and data['surface'] are available
# Extracting the relevant data
grads_A = data['grads']['biochem']['R']  # Shape (n, 2)
# surface_coords = data['surface']         # Shape (n, 3)
surface_coords = test_dict[title]['surface']

# 定义旋转角度（以弧度表示）
theta = np.radians(90)  # 例如旋转45度

# 定义旋转轴，沿着 x = y 轴的方向向量
axis = np.array([1, 1, 0])
axis = axis / np.linalg.norm(axis)  # 单位化

# Rodrigues 旋转公式实现
def rotate_point_cloud(point_cloud, axis, theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    R = (cos_theta * np.eye(3) + 
         sin_theta * np.array([[0, -axis[2], axis[1]],
                               [axis[2], 0, -axis[0]],
                               [-axis[1], axis[0], 0]]) +
         (1 - cos_theta) * np.outer(axis, axis))
    
    return np.dot(point_cloud, R.T)

# 执行旋转
# surface_coords = rotate_point_cloud(surface_coords, axis, theta)
# surface_coords = rotate_point_cloud(surface_coords, np.array([-1, 1, 0]) / np.linalg.norm(np.array([-1, 1, 0])), np.radians(90))
# surface_coords = rotate_point_cloud(surface_coords, np.array([0, 0, 1]), np.radians(45))
# surface_coords = rotate_point_cloud(surface_coords, np.array([1, 0, 0]), np.radians(90))

# Extract the first values of each point
first_values = grads_A[:, 0]  # This is an array of shape (n,)

# Extract the coordinates of each point
x_coords = surface_coords[:, 0]
y_coords = surface_coords[:, 1]
z_coords = surface_coords[:, 2]

# Create a 3D scatter plot
fig = plt.figure(figsize=(7, 5))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with colors representing the first values
sc = ax.scatter(x_coords, y_coords, z_coords, c=first_values, cmap='seismic', marker='o', s=1)

# Add color bar to indicate value distribution
cbar = plt.colorbar(sc, ax=ax)
# cbar.set_label('First Value of grads_A (white represents neutral)')

# Reduce the size of the color bar
cbar.ax.set_position([0.85, 0.3, 0.03, 0.4])  # [left, bottom, width, height]


# Remove ticks from the plot
# ax.set_xticks([])
# ax.set_yticks([])
# ax.set_zticks([])

ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_zlabel('Z Coordinate')

# ax.set_axis_off()

# Set the elevation to 0
ax.view_init(elev=90, azim=-90)  # Elevation is set to 0 degrees

# Show plot
plt.show()

# fig2 materials

## graph + point cloud

In [76]:
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# Step 1: Create a graph with 6 nodes and 10 edges
G = nx.Graph()
edges = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0), (0, 2), (2, 4), (1, 3), (3, 5)]
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Extract the bounds of the graph's layout
graph_x_values = [pos[node][0] for node in pos]
graph_y_values = [pos[node][1] for node in pos]

# Get the min and max of the graph layout
min_x, max_x = min(graph_x_values), max(graph_x_values)
min_y, max_y = min(graph_y_values), max(graph_y_values)

# Step 4: Generate 50 random points within the bounds of the graph layout
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)
points[:, 0] = points[:, 0] * (max_x - min_x) + min_x
points[:, 1] = points[:, 1] * (max_y - min_y) + min_y

# Step 5: Plot the graph
fig = plt.figure(figsize=(5, 5))

# Draw graph nodes and edges
nx.draw(G, pos, with_labels=False, node_size=600, node_color='#DB7800', edge_color='black', font_weight='bold')

# Draw random points as crosses, adjusted to the same scale as the graph nodes
plt.scatter(points[:, 0], points[:, 1], color='red', s=600/3, marker='x', zorder=1)  # Points are 1/3 the size of the nodes, drawn as crosses

# Step 6: Connect each node to its 4 nearest points with dotted lines
for node, node_pos in pos.items():
    node_x, node_y = node_pos
    distances = np.linalg.norm(points - np.array([node_x, node_y]), axis=1)
    nearest_indices = distances.argsort()[:4]  # Get indices of top 4 nearest points
    
    for idx in nearest_indices:
        plt.plot([node_x, points[idx, 0]], [node_y, points[idx, 1]], 'k--', alpha=0.5, zorder=0)
        
# plt.show()
# Path to save the figure
save_path = './figures/fig2_materials'
file_name = 'BC-Graph.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [77]:
import matplotlib.pyplot as plt
import networkx as nx

# Step 1: Create a graph with 6 nodes and 10 edges
G = nx.Graph()
edges = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0), (0, 2), (2, 4), (1, 3), (3, 5)]
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Plot the graph
fig = plt.figure(figsize=(5, 5))

# Draw graph nodes and edges
nx.draw(G, pos, with_labels=False, node_size=600, node_color='skyblue', edge_color='black', font_weight='bold')

# plt.show()
# Path to save the figure
save_path = './figures/fig2_materials'
file_name = 'struc_graph.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [78]:
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Generate 50 random points within a predefined range
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)

# Step 2: Plot the points
fig = plt.figure(figsize=(5, 5))
plt.axis('off')

# Draw random points as crosses
plt.scatter(points[:, 0], points[:, 1], color='red', s=600/3, marker='x', zorder=1)  # Points are drawn as crosses

# plt.show()
# Path to save the figure
save_path = './figures/fig2_materials'
file_name = 'biochem_points.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

## graph + point cloud v2

In [34]:
import os
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# Step 1: Create a graph with 12 nodes and 24 edges
G = nx.Graph()
np.random.seed(42)  # For reproducibility
edges = []
while len(edges) < 16:
    edge = (np.random.randint(0, 12), np.random.randint(0, 12))
    if edge[0] != edge[1] and edge not in edges and (edge[1], edge[0]) not in edges:
        edges.append(edge)
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Extract the bounds of the graph's layout
graph_x_values = [pos[node][0] for node in pos]
graph_y_values = [pos[node][1] for node in pos]

# Get the min and max of the graph layout
min_x, max_x = min(graph_x_values), max(graph_x_values)
min_y, max_y = min(graph_y_values), max(graph_y_values)

# Step 4: Generate 50 random points within the bounds of the graph layout
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)
points[:, 0] = points[:, 0] * (max_x - min_x) + min_x
points[:, 1] = points[:, 1] * (max_y - min_y) + min_y

# Step 5: Plot the graph
fig = plt.figure(figsize=(6, 6))

# Draw graph nodes and edges
nx.draw(G, pos, with_labels=False, node_size=600, node_color='#DB7800', edge_color='black', font_weight='bold')

# Draw random points as crosses, adjusted to the same scale as the graph nodes
plt.scatter(points[:, 0], points[:, 1], color='#DB7800', s=600/3, marker='x', linewidths=6, zorder=1)  # Points are 1/3 the size of the nodes, drawn as crosses

# Step 6: Connect each node to its 4 nearest points with dotted lines
for node, node_pos in pos.items():
    node_x, node_y = node_pos
    distances = np.linalg.norm(points - np.array([node_x, node_y]), axis=1)
    nearest_indices = distances.argsort()[:4]  # Get indices of top 4 nearest points
    
    for idx in nearest_indices:
        plt.plot([node_x, points[idx, 0]], [node_y, points[idx, 1]], 'k--', alpha=0.5, zorder=0)
        
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'BC-Graph_v2.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [10]:
import os
import matplotlib.pyplot as plt
import networkx as nx

# Step 1: Create a graph with 12 nodes and 24 edges
G = nx.Graph()
np.random.seed(42)  # For reproducibility
edges = []
while len(edges) < 16:
    edge = (np.random.randint(0, 12), np.random.randint(0, 12))
    if edge[0] != edge[1] and edge not in edges and (edge[1], edge[0]) not in edges:
        edges.append(edge)
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Plot the graph
fig = plt.figure(figsize=(5, 5))

# Draw graph nodes and edges
nx.draw(G, pos, with_labels=False, node_size=600, node_color='#DB7800', edge_color='black', font_weight='bold')

# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'struc_graph_v2.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [13]:
import os
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Generate 50 random points within a predefined range
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)

# Step 2: Plot the points
fig = plt.figure(figsize=(5, 5))
plt.axis('off')

# Draw random points as crosses
plt.scatter(points[:, 0], points[:, 1], color='#DB7800', s=600/3, marker='x', linewidths=6, zorder=1)  # Points are drawn as crosses

# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'biochem_points_v2.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### add spheres

In [39]:
import os
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from matplotlib.patches import Ellipse

# Step 1: Create a graph with 12 nodes and 16 edges
G = nx.Graph()
np.random.seed(42)  # For reproducibility
edges = []
while len(edges) < 16:
    edge = (np.random.randint(0, 12), np.random.randint(0, 12))
    if edge[0] != edge[1] and edge not in edges and (edge[1], edge[0]) not in edges:
        edges.append(edge)
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Plot the graph
fig, ax = plt.subplots(figsize=(6, 6))

# Draw graph nodes and edges
nx.draw(G, pos, with_labels=False, node_size=600, node_color='#DB7800', edge_color='black', font_weight='bold', ax=ax)

# Step 4: Randomly choose 3 nodes to be centers of spheres
np.random.seed(42)  # For reproducibility
nodes = list(G.nodes)
centers_indices = [4, 9, 11]

# Draw spheres with the selected centers
circle_regions = []
xy_ratio = ax.get_data_ratio()
for center_index in centers_indices:
    center = pos[center_index]
    # Adjust radius based on aspect ratio to ensure the circle appears round
    x_radius = 0.3
    y_radius = 0.3 * (ax.get_data_ratio())  # Adjust y-radius to account for aspect ratio
    
    # Front-facing solid ellipse that looks like a sphere
    ellipse = Ellipse((center[0], center[1]), width=x_radius * 2, height=y_radius * 2, color='#BDD373', alpha=0.3, fill=True, zorder=0)
    ax.add_patch(ellipse)
    circle_regions.append((center, x_radius, y_radius))

# Step 5: Add new nodes to each circle and connect them to existing nodes within the circle
new_node_color = '#739D00'
new_node_indices = range(12, 15)  # New nodes will be numbered 12, 13, 14
new_edges = []

for i, (center, x_radius, y_radius) in enumerate(circle_regions):
    new_node_index = new_node_indices[i]
    # Manually choose an appropriate position within each circle
    new_node_pos = (center[0] - 0.1, center[1] + 0.4)
    pos[new_node_index] = new_node_pos
    G.add_node(new_node_index)
    
    # Connect the new node to nodes that are within the corresponding circle region
    for node_index, (x, y) in pos.items():
        if node_index in nodes:  # Check only existing nodes, not newly added ones
            if ((x - center[0]) ** 2 / x_radius ** 2 + (y - center[1]) ** 2 / y_radius ** 2) <= 1:
                new_edges.append((new_node_index, node_index))

# Step 6: Draw the graph with the new nodes
nx.draw(G, pos, with_labels=False, node_size=600, node_color=['#DB7800' if node < 12 else new_node_color for node in G.nodes], edge_color='black', font_weight='bold', ax=ax)

# Draw the newly added edges as dotted lines, below nodes
for edge in new_edges:
    x_coords = [pos[edge[0]][0], pos[edge[1]][0]]
    y_coords = [pos[edge[0]][1], pos[edge[1]][1]]
    ax.plot(x_coords, y_coords, linestyle=(0, (3, 5, 1, 5)), color='black', alpha=0.7, zorder=-1)  # More space between dashes, zorder=-1 for lower layer

# Step 7: Add a new node in the bottom-right corner with color B63648
bottom_right_node_index = 15
# Set position to max x and min y of all original nodes
max_x = max(pos[node][0] for node in range(12))
min_y = min(pos[node][1] for node in range(12))
bottom_right_node_pos = (max_x, min_y)
pos[bottom_right_node_index] = bottom_right_node_pos
G.add_node(bottom_right_node_index)

# Connect the new bottom-right node to all other nodes except the newly added ones (12, 13, 14)
for node_index in range(12):
    G.add_edge(bottom_right_node_index, node_index)

# Draw the new bottom-right node
nx.draw_networkx_nodes(G, pos, nodelist=[bottom_right_node_index], node_size=600, node_color='#B63648', ax=ax)

# Draw the newly added edges as dotted lines, below nodes
for node_index in range(12):
    x_coords = [pos[bottom_right_node_index][0], pos[node_index][0]]
    y_coords = [pos[bottom_right_node_index][1], pos[node_index][1]]
    ax.plot(x_coords, y_coords, linestyle=(0, (3, 5, 1, 5)), color='black', alpha=0.7, zorder=-1)  # More space between dashes, zorder=-1 for lower layer

# # Draw node labels with numbers
# for node, (x, y) in pos.items():
#     ax.text(x, y, str(node), fontsize=12, ha='center', va='center', color='black')

# plt.show()
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'struc_graph_with_spheres.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)


import os
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse
import networkx as nx

# Step 1: Create a graph with 12 nodes and 24 edges
G = nx.Graph()
np.random.seed(42)  # For reproducibility
edges = []
while len(edges) < 16:
    edge = (np.random.randint(0, 12), np.random.randint(0, 12))
    if edge[0] != edge[1] and edge not in edges and (edge[1], edge[0]) not in edges:
        edges.append(edge)
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Extract the bounds of the graph's layout
graph_x_values = [pos[node][0] for node in pos]
graph_y_values = [pos[node][1] for node in pos]

# Get the min and max of the graph layout
min_x, max_x = min(graph_x_values), max(graph_x_values)
min_y, max_y = min(graph_y_values), max(graph_y_values)

# Step 1: Generate 50 random points within a predefined range
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)
# Rescale points to match the graph's coordinate scale
points[:, 0] = points[:, 0] * (max_x - min_x) + min_x
points[:, 1] = points[:, 1] * (max_y - min_y) + min_y

# Step 3: Plot the points
fig, ax = plt.subplots(figsize=(5, 5))
# Expand the limits slightly to provide padding around the graph
padding = 0.15
ax.set_xlim(min_x - padding, max_x + padding)
ax.set_ylim(min_y - padding * xy_ratio, max_y + padding * xy_ratio)
plt.axis('off')

# Draw random points as crosses
plt.scatter(points[:, 0], points[:, 1], color='#DB7800', s=600/3, marker='x', linewidths=6, zorder=1)  # Points are drawn as crosses

# Draw spheres with the selected centers
centers_indices = [4, 9, 11]
circle_regions = []
for center_index in centers_indices:
    center = pos[center_index]
    # Adjust radius based on aspect ratio to ensure the circle appears round
    x_radius = 0.3
    y_radius = 0.3 * xy_ratio  # Adjust y-radius to account for aspect ratio
    
    # Front-facing solid ellipse that looks like a sphere
    ellipse = Ellipse((center[0], center[1]), width=x_radius * 2, height=y_radius * 2, color='#BDD373', alpha=0.3, fill=True, zorder=0)
    ax.add_patch(ellipse)
    circle_regions.append((center, x_radius, y_radius))

    # Draw a point at the center of each circle
    plt.scatter(center[0], center[1], color='#739D00', s=600/3, marker='x', linewidths=6, zorder=2)

# Draw a point at the center of the plot
center_x = (min_x + max_x) / 2
center_y = (min_y + max_y) / 2
plt.scatter(center_x, center_y, color='#B63648', s=600/3, marker='x', linewidths=6, zorder=3)

# plt.show()
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'biochem_points_with_spheres.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### one point

In [19]:
import os
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse
import networkx as nx

# Step 1: Create a graph with 12 nodes and 16 edges
G = nx.Graph()
np.random.seed(42)  # For reproducibility
edges = []
while len(edges) < 16:
    edge = (np.random.randint(0, 12), np.random.randint(0, 12))
    if edge[0] != edge[1] and edge not in edges and (edge[1], edge[0]) not in edges:
        edges.append(edge)
G.add_edges_from(edges)

# Step 2: Create node positions using a spring layout (for esthetic purposes)
pos = nx.spring_layout(G)

# Step 3: Extract the bounds of the graph's layout
graph_x_values = [pos[node][0] for node in pos]
graph_y_values = [pos[node][1] for node in pos]

# Get the min and max of the graph layout
min_x, max_x = min(graph_x_values), max(graph_x_values)
min_y, max_y = min(graph_y_values), max(graph_y_values)

# Step 4: Generate 50 random points within a predefined range
np.random.seed(42)  # For reproducibility
points = np.random.rand(50, 2)
# Rescale points to match the graph's coordinate scale
points[:, 0] = points[:, 0] * (max_x - min_x) + min_x
points[:, 1] = points[:, 1] * (max_y - min_y) + min_y

# Expand the limits slightly to provide padding around the graph
padding = 0.15

# Step 6: Identify the point closest to the center of the top-right quadrant
# Calculate the center of the top-right quadrant
quad_center_x = (max_x + min_x) / 2 - (max_x - min_x) / 4
quad_center_y = (max_y + min_y) / 2 - (max_y - min_y) / 4

# Calculate distances of all points to the center of the top-right quadrant
distances = np.sqrt((points[:, 0] - quad_center_x) ** 2 + (points[:, 1] - quad_center_y) ** 2)
closest_point_index = np.argmin(distances)
closest_point = points[closest_point_index]

# Step 7: Plot a new plot focusing on this closest point as the center
new_width = (max_x - min_x) / 2
new_height = (max_y - min_y) / 2
new_min_x = closest_point[0] - new_width / 2
new_max_x = closest_point[0] + new_width / 2
new_min_y = closest_point[1] - new_height / 2
new_max_y = closest_point[1] + new_height / 2

# Filter points that fall within the new bounds
filtered_points = points[
    (points[:, 0] >= new_min_x) & (points[:, 0] <= new_max_x) &
    (points[:, 1] >= new_min_y) & (points[:, 1] <= new_max_y)
]

# Step 8: Plot the filtered points
fig, ax = plt.subplots(figsize=(5, 5))
ax.set_xlim(new_min_x, new_max_x)
ax.set_ylim(new_min_y, new_max_y)
plt.axis('off')

# Draw filtered points as crosses
plt.scatter(filtered_points[:, 0], filtered_points[:, 1], color='#DB7800', s=600/3, marker='x', linewidths=6, zorder=1)

# Step 9: Draw 4 circles centered at the closest point
circle_radii = [new_width / 8, new_width / 4, 3 * new_width / 8, new_width / 2]
for radius in circle_radii:
    ellipse = Ellipse(
        (closest_point[0], closest_point[1]),
        width=2 * radius,  # Width is diameter
        height=2 * radius * (new_height / new_width),  # Adjust height for aspect ratio
        edgecolor='none',
        facecolor='skyblue',
        alpha=0.2,
        zorder=0
    )
    ax.add_patch(ellipse)

# Highlight the center point
plt.scatter(closest_point[0], closest_point[1], color='#0000BB', s=800/3, marker='x', linewidths=6, zorder=2)

plt.scatter(closest_point[0] + 0.012, closest_point[1], color='#739D00', s=600/3, marker='x', linewidths=6, zorder=1)
plt.scatter(closest_point[0] + 0.006, closest_point[1], color='#B63648', s=600/3, marker='x', linewidths=6, zorder=1)

# plt.show()
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'one_biochem_point.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

### for legend

In [28]:
fig = plt.figure(figsize=(1, 1))
plt.scatter(0, 0, color='#739D00', s=600/3, marker='x', linewidths=6, zorder=1)
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'local_point_legend.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [30]:
fig = plt.figure(figsize=(1, 1))
plt.scatter(0, 0, color='#B63648', s=600/3, marker='x', linewidths=6, zorder=1)
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'global_point_legend.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [32]:
fig = plt.figure(figsize=(1, 1))
plt.scatter(0, 0, color='#0000BB', s=600/3, marker='x', linewidths=6, zorder=1)
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'center_point_legend.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)

In [ ]:
fig = plt.figure(figsize=(1, 1))
plt.scatter(0, 0, color='#DB7800', s=600/3, marker='x', linewidths=6, zorder=1)
# Save the figure to the specified path
save_path = './figures/fig2_materials'
file_name = 'original_point_legend.png'

# Create the directory if it doesn't exist
if not os.path.exists(save_path):
    os.makedirs(save_path)
plt.savefig(os.path.join(save_path, file_name))
plt.close(fig)